### ISSUE TITLE
Let HNC disable propagation Rancher-propagated objects

### ISSUE THREAD

**Issue by ichmachnixichgucknur** [kubernetes-sigs/hierarchical-namespaces#104]
Hi,
I am new to the HNC and wondering how to disable the default resources (roles and rolebinding)?
I'd like to use the HNC just to propagate networkpolicies and resource limits to the child namespaces.

**Comment by ichmachnixichgucknur** [comment]
We are using Rancher. Rancher does his own magic on permissions, roles etc. .
I tried some stuff with the HNC and it fits perfectly to distribute networkpolicies and resource limits, but we get into problems with roles and rolebindings. So if I could disable the defaults, that would be really great.
I am not a go dev - but if you are willing to guide me ... I can try to.

**Comment by ichmachnixichgucknur** [comment]
yes, exactly. Rancher is organized in projects and projects inherit namespaces. that's just done using annotations. permissions are set on the projects and applied by rancher to the namespaces.
this leads to some rolebindings that are the same all over the clusters.

using the HNC I get these errors, because it wants to delete an account that is created by rancher:
`{"level":"info","ts":1634650448.2220306,"logger":"validators.Object","msg":"Denied","resource":{"group":"rbac.authorization.k8s.io","version":"v1","resource":"rolebindings"},"ns":"netpoltest-101","nm":"rb-pmsrakgptq","op":"DELETE","user":"system:serviceaccount:cattle-system:kontainer-engine","code":403,"reason":"Forbidden","message":"Cannot delete object propagated from namespace \"my-root-ns\""}`

**Comment by ichmachnixichgucknur** [comment]
We will try and come back to you.

**Comment by ichmachnixichgucknur** [comment]
> * We'll need to find a way to ensure that the _initial_ HNCConfiguration object has Roles and Rolebindings included, since I want _something_ to work out of the box. This isn't a big deal, but will need to be coded and tested.

Yes, I did not find the right part to do it. The easiest would be to deploy a hnc configuration including this types if no config exists.

> * This won't help cases where you want to propagate _some_ RBAC permissions. In that case, you'd still need to do the per-object-level filtering I mentioned.

Correct.
 
> So since we need per-object-level filtering anyway, maybe we can start by just building that?

Do we have two issues here? One thing is to be more flexible having the roles and rolebindings as flexible as the other resources are. That would work with the changes we did, currently missing the default role and rolebinding (so that tests will run, too).
The second thing would be the per per-object filtering - maybe as a cli-parameter.

**Comment by adrianludwin** [comment]
I believe this was recently fixed.

/close
