### ISSUE TITLE
darwin_arm64 native support for kubectl plugin

### ISSUE THREAD

**Issue by onesail** [kubernetes-sigs/hierarchical-namespaces#113]
for darwin only amd64 is listed as HNC-platform.
with apple silicon being the only cpu available on mabooks in the long run native support is required

**Comment by adrianludwin** [comment]
Someone's trying to fix this in #111

**Comment by adrianludwin** [comment]
The change has been checked in so it will be in the next release, sorry I didn't close this bug. But it is fixed, and will be available soon.

/close
