### ISSUE TITLE
HNC: Add webhook rules to deny editing namespace tree labels

### ISSUE THREAD

**Issue by yiqigao217** [kubernetes-sigs/hierarchical-namespaces#12]
<a href="https://github.com/yiqigao217"><img src="https://avatars.githubusercontent.com/u/51385444?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [yiqigao217](https://github.com/yiqigao217)**
_Tuesday Apr 27, 2021 at 20:10 GMT_
_Originally opened as https://github.com/kubernetes-sigs/multi-tenancy/issues/1494_

----

Currently, the tree labels on namespaces can be edited without webhook blocking it. HNC will re-reconcile the namespace to update the tree labels.

We need to have our webhooks to block edits on namespace tree labels.

**Comment by RealHarshThakur** [comment]
@yiqigao217 Can I take this up? 

Just had a question:
* Do we have a field manager/owner to identify only HNC is allowed to make changes to labels? If so, is that what we can use to reject requests from other field manager/owner?

**Comment by adrianludwin** [comment]
@RealHarshThakur sorry I didn't see this! Yiqi's not working on HNC anymore. Yes, this would be a nice and fairly straightforward change for you to make if you're still interested.

The namespace validators are [here](https://github.com/kubernetes-sigs/hierarchical-namespaces/blob/master/internal/validators/namespace.go). As you can see on [this line](https://github.com/kubernetes-sigs/hierarchical-namespaces/blob/3090e7337b3a19e686cbb720f7f560de5473435e/internal/validators/namespace.go#L46), the first thing we check is whether the change is being made by the HNC service account, and if so, we allow all changes. So the rest of the validator can safely deny anything that anyone who's _not_ HNC shouldn't be allowed to do.

**Comment by RealHarshThakur** [comment]
@adrianludwin Thanks for the reply. Just to be sure:  I  just need to add a check [here](https://github.com/kubernetes-sigs/hierarchical-namespaces/blob/master/internal/validators/namespace.go#L88) and deny all requests trying to modify the tree labels on a namespace, right?

**Comment by adrianludwin** [comment]
Yes, that's roughly the right place. We also need to check Create operations as well since we don't want someone creating a namespace with the (wrong) labels on them.

We also try not to reject changes that don't contain _new_ problems. E.g. if the namespace _already_ has the wrong label, we shouldn't reject the _new_ change that might be unrelated. Check out [this line](https://github.com/kubernetes-sigs/hierarchical-namespaces/blob/master/internal/validators/namespace.go#L114) for an example of this logic. In fact, your function might look quite similar to this - but also make sure nothing's _removed_ either.

**Comment by rahulii** [comment]
@adrianludwin If its still needed, I can take this up! Could you point me to the updated place where we need to make a change, the above comments seem outdated

**Comment by RealHarshThakur** [comment]
@rahulii  I've already made a PR for this : https://github.com/kubernetes-sigs/hierarchical-namespaces/pull/51

**Comment by rahulii** [comment]
oh damn! you should 've linked your PR to the issue ! I was looking into it since yesterday
 :/

**Comment by RealHarshThakur** [comment]
Apologies. Hope you find another issue to work on

**Comment by erikgb** [comment]
Was this issue fully resolved by https://github.com/kubernetes-sigs/hierarchical-namespaces/pull/51, and can be closed, or this there anything remaining?

**Comment by RealHarshThakur** [comment]
Yes, I think we can close this issue.
