### ISSUE TITLE
Could not update the hierarchical configuration - on Openshift 

### ISSUE THREAD

**Issue by arturobrzut** [kubernetes-sigs/hierarchical-namespaces#140]
Environment Openshift 4.8
HNC v0.9.0

Hi 
I install HNC on Openshift cluster 4.8
And I have such issue:
```
kubectl create namespace my-parent
namespace/my-parent created

kubectl hns create -n my-parent my-child1   
Successfully created "my-child1" subnamespace anchor in "my-parent" namespace

kubectl create namespace my-child2
namespace/my-child2 created

kubectl hns set my-child2 --parent my-parent
Setting the parent of my-child2 to my-parent

Could not update the hierarchical configuration of my-child2.
Reason: admission webhook "hierarchyconfigurations.hnc.x-k8s.io" denied the request: Cannot update hierarchy because it would overwrite the following object(s):
  * Namespace "my-child2": system:image-pullers (rbac.authorization.k8s.io/v1, Kind=RoleBinding)
  * Namespace "my-child2": system:image-builders (rbac.authorization.k8s.io/v1, Kind=RoleBinding)
  * Namespace "my-child2": system:deployers (rbac.authorization.k8s.io/v1, Kind=RoleBinding)
To fix this, please rename or remove the conflicting objects first.
```

Can we turn off checking some OCP resource in HNC?

**Comment by adrianludwin** [comment]
Are you able to add annotations to the RBAC role bindings? If so, you can
use exceptions
<https://github.com/kubernetes-sigs/hierarchical-namespaces/blob/master/docs/user-guide/how-to.md#use-limit-propagation>
to disable annotations for them. Otherwise, is there a systematic way to
identify which objects *shouldn't* be propagated, like a name or a label?
If so, we could add all the necessary OpenShift information here
<https://github.com/kubernetes-sigs/hierarchical-namespaces/blob/082779afa4b5bdd6c9231906f3639f41d79a6999/internal/selectors/selectors.go#L161>
for
the next version of HNC.

**Comment by arturobrzut** [comment]
@adrianludwin 
It works when I add annotations in parent namespace resources

but I want to add PR which exclude this 3 RoleBinding 
I will prepare it

**Comment by adrianludwin** [comment]
What's the criteria you'll use to exclude these? Is it a well-known label?
If so, please include documentation here:
https://github.com/kubernetes-sigs/hierarchical-namespaces/blob/master/docs/user-guide/concepts.md#built-in-exceptions

Thanks!

**Comment by arturobrzut** [comment]
Ok I will describe it in doc 

https://github.com/kubernetes-sigs/hierarchical-namespaces/blob/master/docs/user-guide/concepts.md#built-in-exceptions

these 3 RoleBindings are always created by Openshift
![image](https://user-images.githubusercontent.com/54812713/152006503-0a9dcf31-2275-4357-bb9c-014dc149e374.png)

**Comment by adrianludwin** [comment]
This might be the right time to turn this into a CLI since this list keeps
getting longer.

e.g.:
--exclude-propagation-by-name="group/version:Kind:nameregex"
--exclude-propagation-by-label="labelkey:labelvalue"

**Comment by arturobrzut** [comment]
and now maybe exclude by annotations 
e.g. 
if openshift annotation exists do not propagate

**Comment by erikgb** [comment]
As already suggested above, I think it would make more sense to exclude HNC propagation of roles/rolebindings with names that have a `system:` prefix. And not do something tailored for Openshift to resolve this issue. IMO the Kubernetes documentation could be used to support this point of view: https://kubernetes.io/docs/reference/access-authn-authz/rbac/#default-roles-and-role-bindings. The note addresses clusterroles/clusterrolebindings, but I think it could be argued that the same principle should/could be applied to roles/rolebindings in HNC.
