### ISSUE TITLE
HNC: Show right namespaces in `kubectl hns tree --all-namespaces`

### ISSUE THREAD

**Issue by yiqigao217** [kubernetes-sigs/hierarchical-namespaces#15]
<a href="https://github.com/yiqigao217"><img src="https://avatars.githubusercontent.com/u/51385444?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [yiqigao217](https://github.com/yiqigao217)**
_Thursday Apr 15, 2021 at 17:36 GMT_
_Originally opened as https://github.com/kubernetes-sigs/multi-tenancy/issues/1478_

----

1) Namespaces with conditions are missing in the `kubectl hns tree --all-namespaces` output.
2) Another improvement would be adding additional highlights on excluded namespaces in `kubectl hns` plugins to differentiate the namespaces.

Here's what I got currently:
```
$ kubectl get ns
NAME              STATUS        AGE
default           Active        22h
hnc-system        Active        21h
kube-node-lease   Active        22h
kube-public       Active        22h
kube-system       Active        22h
service-2         Terminating   47m
team-a            Active        47m
team-b            Active        47m


$ kubectl hns tree --all-namespaces  #### team-a and team-b are not listed here
default
hnc-system
kube-node-lease
kube-public
kube-system
service-2

Conditions:
1) ActivitiesHalted (ParentMissing): Parent "acme-org" does not exist


$ kubectl  hns tree team-a
team-a (1)

Conditions:
1) ActivitiesHalted (ParentMissing): Parent "acme-org" does not exist


$ kubectl hns tree team-b
team-b (1)

Conditions:
1) ActivitiesHalted (ParentMissing): Parent "acme-org" does not exist
```

**Comment by yiqigao217** [comment]
<a href="https://github.com/FingerLiu"><img src="https://avatars.githubusercontent.com/u/3981064?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [FingerLiu](https://github.com/FingerLiu)**
_Monday Apr 19, 2021 at 03:31 GMT_

----

multi-tenancy is very useful, I'd like to work on this.
/assign

**Comment by yiqigao217** [comment]
<a href="https://github.com/FingerLiu"><img src="https://avatars.githubusercontent.com/u/3981064?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [FingerLiu](https://github.com/FingerLiu)**
_Monday Apr 19, 2021 at 03:45 GMT_

----

@yiqigao217 since I am new here, would you please give me a hint where should I start?

**Comment by yiqigao217** [comment]
<a href="https://github.com/yiqigao217"><img src="https://avatars.githubusercontent.com/u/51385444?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [yiqigao217](https://github.com/yiqigao217)**
_Tuesday Apr 27, 2021 at 20:41 GMT_

----

Hi @FingerLiu  sorry for the late reply. The `kubectl hns tree` command are defined in https://github.com/kubernetes-sigs/multi-tenancy/blob/master/incubator/hnc/internal/kubectl/tree.go .

Please note only namespaces **with conditions** are not shown in the `kubectl hns tree --all-namespaces`. The easiest way to produce a condition is to delete the parent namespace, so that the namespace would have `ActivitiesHalted (ParentMissing)` condition that you can test with.

To test your kubectl hns plugin, you may need to remove the current kubectl hns plugin if you already have one and run `make kubectl`. You can find the kubectl plugin path at https://github.com/kubernetes-sigs/multi-tenancy/blob/master/incubator/hnc/Makefile#L120-L121.

**Comment by yiqigao217** [comment]
<a href="https://github.com/FingerLiu"><img src="https://avatars.githubusercontent.com/u/3981064?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [FingerLiu](https://github.com/FingerLiu)**
_Wednesday Apr 28, 2021 at 02:59 GMT_

----

It looks clear to me now, thanks.

**Comment by FingerLiu** [comment]
@yiqigao217  Hi, a little question here, after the parent namespace deleted,  why do not we do Cascade Delete?
In this case, if acme-org is deleted, why not we delete team-a and team-b? If so, the current issue should not be triggered anymore

**Comment by yiqigao217** [comment]
Hi @FingerLiu this is a good question! We do have a [cascading deletion option](https://github.com/kubernetes-sigs/hierarchical-namespaces/blob/master/docs/user-guide/how-to.md#delete-a-subnamespace
) for `subnamespaces` (see definition of [subnamespaces](https://github.com/kubernetes-sigs/hierarchical-namespaces/blob/master/docs/user-guide/concepts.md#subnamespaces-and-full-namespaces)).

However, for full namespaces, or even subnamespaces when `allowCascadingDeletion` field is not set to `true` and the webhook is bypassed (when deleting parent with subnamespaces is allowed), we would still come across this issue.

Please note there is also an open issue on preventing orphan, see #30 .
