### ISSUE TITLE
Release 1.0 and introduction for production readiness?

### ISSUE THREAD

**Issue by catshout** [kubernetes-sigs/hierarchical-namespaces#150]
Great idea, concept and implementation!

Latest statement about production readiness said end of  2021. Are there any updated plans when this will become part of k8s standard itself?

Best
Gerald

**Comment by pankajmt** [comment]
I had a similar question. When is 1.0 likely to be available now? So that we could start with using 0.9 in pre-production!

**Comment by adrianludwin** [comment]
Hey all, thanks for the questions (and sorry for the delay). We were planning on releasing v1.0 but there have been a few feature requests to improve productionization and stability (e.g. #139 ) so we decided to hold the release for that. We're not planning any other major new features though, and HNC is already being used in production by Mercari.

We don't have any plans to preinstall HNC on GKE, but you can follow the official release instructions for v0.9 here: https://github.com/kubernetes-sigs/hierarchical-namespaces/releases/tag/v0.9.0. No need to build from source :)

**Comment by Mais316** [comment]
@adrianludwin  sorry for asking again, but do we have any date estimate for v1.0 release as we have a major project on hold waiting for that release, what would be the consequences of building v1.0 from current main.

**Comment by adrianludwin** [comment]
I just finished approving the final code PRs this morning. I'll update some documentation and create the first release candidate tomorrow; if all goes well it should be out by the end of next week. Sorry for all the delays.

**Comment by adrianludwin** [comment]
Hey folks, the release candidate is out! Please check it out at https://github.com/kubernetes-sigs/hierarchical-namespaces/releases/tag/v1.0.0-rc1 and let me know if it works for you. There are no known changes planned for v1.0.0 so this should be the final version unless you run into any issues. Thanks!

**Comment by Mais316** [comment]
@adrianludwin thanks a lot  for all ur efforts :)

**Comment by adrianludwin** [comment]
[HNC v1.0.0 is now available](https://github.com/kubernetes-sigs/hierarchical-namespaces/releases/tag/v1.0.0)! Please ensure that you're subscribed to [kubernetes-hnc-announce](https://groups.google.com/g/kubernetes-hnc-announce) for important announcements.

Thanks!

(PS - @Mais316 - gotta love Inside Out!)

/close
