### ISSUE TITLE
Only create per-object webhooks for configured types

### ISSUE THREAD

**Issue by adrianludwin** [kubernetes-sigs/hierarchical-namespaces#152]
We currently create [one almighty "object" webhook](https://github.com/kubernetes-sigs/hierarchical-namespaces/blob/281b24ff4c6d9fbbed59f6ac473b9c3cad79450f/config/webhook/manifests.yaml#L83) that, if broken, can effectively block every object operation in the entire cluster (minus critical system namespaces), even for objects that are not being monitored by HNC.

We should modify the `HNCConfiguration` reconciler to dynamically generate webhooks _only_ for the objects types that are being propagated by HNC. Note that we need to insert new webhooks into the existing webhook config, since HNC's copy of cert-controller [mentions the HNC webhook config by name](https://github.com/kubernetes-sigs/hierarchical-namespaces/blob/281b24ff4c6d9fbbed59f6ac473b9c3cad79450f/internal/setup/webhooks.go#L21), so creating a whole new webhook config won't work. But that should be pretty easy.

I'm guessing the best place to do this is to build a function similar to `[syncObjectReconcilers](https://github.com/kubernetes-sigs/hierarchical-namespaces/blob/281b24ff4c6d9fbbed59f6ac473b9c3cad79450f/internal/hncconfig/reconciler.go#L268)`, maybe called `syncObjectWebhookConfigs` or something like that.

I don't _think_ this is a requirement for v1.0 but it would be nice if you felt like getting it in.

/assign @erikgb 
/cc @rjbez17

**Comment by adrianludwin** [comment]
Thanks for working on this :)

**Comment by mzain** [comment]
Hey Folks,
Checking if this is still being worked on?

**Comment by adrianludwin** [comment]
Sorry, been very busy but looking at that PR now

**Comment by omaratdgtl** [comment]
Hey Folks,
Checking if this is still being worked on?

**Comment by rjbez17** [comment]
Hey @omaratdgtl There are only a few things left in the PR to clean up and then we can get it merged. Unfortunately those working on the PR are quite busy. If you wanted to take over the PR here https://github.com/kubernetes-sigs/hierarchical-namespaces/pull/285 and clean up the last few items we can get it reviewed and merged!
