### ISSUE TITLE
[feature] Add quotas sum

### ISSUE THREAD

**Issue by zfrhv** [kubernetes-sigs/hierarchical-namespaces#157]
Lets say I create a namespace and call it `main`. then i give it `quota` with 10 cpu.
now i give admin/edit permissions to `person1` on that namespace.

Assuming `person1` creates subnamespace named `child1` from `main`.
I expect the subnamespace to have not more than 10 cpu.

Would it be possible to:
1. calculate the sum of requests + limits from all SubNamespaces and not only from current namespace.
2. allow `person1` to manage quotas for himself in his subnamespaces.

the end goal is for all subnamespaces resources to not pass the `quota` of the `main` namespace.

**Comment by adrianludwin** [comment]
Is this the kind of thing that you're looking for? We're considering adding
it to HNC.

https://cloud.google.com/anthos-config-management/docs/how-to/using-hierarchical-resource-quotas

**Comment by zfrhv** [comment]
yesss!
(i actually found HNC [here](https://github.com/kubernetes/kubernetes/issues/108709) by searching for something that can manage quotas like that)

**Comment by adrianludwin** [comment]
Your timing is good; it will likely be in the next release of HNC. See this proposed commit on my personal repo (note that this is _not_ merged yet).

https://github.com/adrianludwin/hierarchical-namespaces/commit/21e5a8af9c4c380e5982c8bbc150e7293d78d871

**Comment by zfrhv** [comment]
cool !
(should i keep this case open?)

**Comment by adrianludwin** [comment]
Up to you :) But I'm happy to close it as it will be fixed shortly
regardless.

**Comment by zfrhv** [comment]
yea it will be implemented anyways so i guess i can close

thank you
