### ISSUE TITLE
Convert a full namespace to a subns and to be children of another subns

### ISSUE THREAD

**Issue by weilaaa** [kubernetes-sigs/hierarchical-namespaces#191]
I noticed that full namespaces can be children of subnamespaces by doing `kubectl hns set staging --parent service-4`, so if we need a way to convert a full namespace to a subnamespace and to be children of another subnamespace. just like:

```bash
team-a
├── [s] service-2
└── [s] service-4
     └── [s] staging
```

**Why we need it?**
In some scenarios, our cluster already have a lot of full namespaces, and then we wanna take over them by subnamespaces way.

**Comment by weilaaa** [comment]
I read codes and had a try that by two steps, I can take over full namespace as a subnamespace manually.
1. add annotations to full namespaces `ns-1`, example: `hnc.x-k8s.io/subnamespace-of: team-a`
2. create subnamespaceanchor with same name: `kubectl hns create ns-1 -n team-a`

**Comment by adrianludwin** [comment]
Yes, that's the right way to solve this problem. Are you asking for a
change in behaviour? And why are you trying to convert a full namespace
into a subnamespace? Thanks!

**Comment by weilaaa** [comment]
Yep, I'm asking for a behavior change. As I said in `Why we need it`, assumed that our k8s cluster already had a lot of full namespaces, and I want to take over them by subnamespaces way, cause I want the features of [subnamespaces-deep-dive](https://github.com/kubernetes-sigs/hierarchical-namespaces/blob/master/docs/user-guide/quickstart.md#subnamespaces-deep-dive) rather than using simple HierarchyConfiguration.

**Comment by weilaaa** [comment]
I'm willing to have a try if you think it alright.

**Comment by weilaaa** [comment]
Thanks for u answers. Everything works follow twos steps. By the way, can you easily reveal when the HA will be stable?

**Comment by adrianludwin** [comment]
I think that in v1.1 (probably out in a month or two) we'll upgrade it to
"beta," which means that we think it _should_ work but there might still be
some bugs or instability.
