### ISSUE TITLE
Backport #168 to v1.0 branch

### ISSUE THREAD

**Issue by adrianludwin** [kubernetes-sigs/hierarchical-namespaces#193]
/assign @adamdougal

**Comment by adrianludwin** [comment]
Hey @adamdougal, I can't assign this to you but I've just filed this to track backporting #168 to the v1.0 branch. Thanks!

**Comment by adamdougal** [comment]
Np, raised a PR here! https://github.com/kubernetes-sigs/hierarchical-namespaces/pull/194

**Comment by adrianludwin** [comment]
#194 has been merged, thanks @adamdougal !

/close
