### ISSUE TITLE
Allow propagation of resources per root namespace

### ISSUE THREAD

**Issue by yiqigao217** [kubernetes-sigs/hierarchical-namespaces#20]
<a href="https://github.com/hferentschik"><img src="https://avatars.githubusercontent.com/u/296354?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [hferentschik](https://github.com/hferentschik)**
_Tuesday Mar 16, 2021 at 09:25 GMT_
_Originally opened as https://github.com/kubernetes-sigs/multi-tenancy/issues/1435_

----

Currently, you can only globally (via the HNCConfiguration) configure the resources to be propagated, eg Secrets. However, propagation might differ between different root namespaces. 

IMO it would be nice to be able to configure propagation rules per hierarchy. 

For example, we are implementing an application that uses HNC to create and delete dynamically sub-namespaces. For the root namespace of our application and its children we want to propagate Secrets, but not for any other namespace.

ATM, we are installing HNC as part of our Helm chart, but we also have a flag where the HNC install is skipped in the case HNC is already installed on the cluster. In the latter case, our applications need to propagate Secrets might be in conflict with already existing usage of HNC.  

Hope this makes sense. I have no idea whether there might be a technical limitation which propagation rules could not be configured per hierarchy.

**Comment by yiqigao217** [comment]
<a href="https://github.com/adrianludwin"><img src="https://avatars.githubusercontent.com/u/20559844?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [adrianludwin](https://github.com/adrianludwin)**
_Tuesday Mar 16, 2021 at 14:35 GMT_

----

There's no _technical_ barrier to doing this, but it's a pretty complicated _design_ problem. For example, assume we add an "allow-propagate" mode as suggested in #1436. Does a "force-propagate" in a parent override an "allow-propagate" in a child, or vice versa? What's the API for controlling all this? I'm sure we can answer all these (after all, filesystems have done this kind of thing for years) but it will take nontrivial effort. The testing will also be quite complicated.

If you'd like to have a go at writing a design doc stating the precise API and semantics of this feature, I'd be happy to have a look, and then review any resulting PRs. However, before I ask the core team to work on this, I'd need to see more evidence of a strong demand. I hope this makes sense!

**Comment by adrianludwin** [comment]
Hi @hferentschik , I don't think anyone's going to work on this unless there's a design doc that answers the questions I raised earlier on. If you'd like to write such a doc I'd be happy to look at it!
