### ISSUE TITLE
HNC: Multiarch images (e.g. arm64)

### ISSUE THREAD

**Issue by JohannesLamberts** [kubernetes-sigs/hierarchical-namespaces#201]
Hi,

we just ran into issue that the image gcr.io/k8s-staging-multitenancy/hnc-manager:v1.0.0 would not start in a ARM-Cluster.

The issue has already been raised in https://github.com/kubernetes-sigs/multi-tenancy/issues/1383 and should have been fixed by https://github.com/kubernetes-sigs/hierarchical-namespaces/pull/45 [on 5 Jul 2021](https://github.com/kubernetes-sigs/hierarchical-namespaces/pull/45#event-4979190875).

I'm not quite sure, if the particular image that I'm referring to is unrelated to the PR mentioned above or if I'm missing something else.

When inspecting the image via `docker inspect gcr.io/k8s-staging-multitenancy/hnc-manager:v1.0.0` the only architecture I get is amd64. Same goes for the latest tag `master-34837c2`.

Can you provide any insight into whether multi-arch images are available and I missed some crucial part of information or whether there are no multi-arch images available at the moment and we should switch to AMD until such an image is ready?

Thanks!

**Comment by rjbez17** [comment]
I was working on [this](https://github.com/kubernetes-sigs/hierarchical-namespaces/issues/164) and our current build pipeline is setup for this but I was stuck on some QEMU issues. I haven't had time to look at it all, but if you have some suggestions I'm happy to hear it. 

If you can get the cloudbuild.yaml to work with ARM in cloud build, I'll happily integrate it. As of now, I can get it working on my mac just fine, but not in cloud build. I've also not spent a huge amount of time on this either so it may be something simple I missed.

**Comment by Nopzen** [comment]
@rjbez17 any chance you got around back to this :D? sadly I'm not able to help out on the issue, but would really love a arm64 build as well for my k3s cluster :)

Or maybe @adrianludwin since april last year have there been any talks about perhaps supporting this officially?

**Comment by rjbez17** [comment]
/remove-lifecycle rotten

I can take another look now that its been a while, but don't have a ton of time to dedicate to the project at the moment.

**Comment by Nopzen** [comment]
@rjbez17 No worries, I would love to help but I'm not sure if I would be of great help, as I dont have access to the GCP Cloudbuild.

**Comment by DoTruong1** [comment]
Hey, are there any updates on this?
