### ISSUE TITLE
Use Prow to create cherry-pick PR to release branches

### ISSUE THREAD

**Issue by erikgb** [kubernetes-sigs/hierarchical-namespaces#208]
I notice that when we occasionally consider a PR a bugfix, that we want to include in a patch release, we need to ask our users to open a new PR against the release branch. This is not optimal, and I think Prow can help us with this. At least, I've seen that done in other K8s projects.

Looking at the Prow command reference: https://prow.k8s.io/command-help, it is listed as the first command.

But for HNC, it is not listed: https://prow.k8s.io/command-help?repo=kubernetes-sigs%2Fhierarchical-namespaces, so I think we need to something to set it up.

**Comment by erikgb** [comment]
@rjbez17 maybe you know how to set this up?

**Comment by rjbez17** [comment]
I think I found where to do this, I'll work on it this week.

**Comment by adrianludwin** [comment]
Cool, thanks!
