### ISSUE TITLE
BUG: Can not add Label/Annotations after enabling propagation

### ISSUE THREAD

**Issue by raz-bn** [kubernetes-sigs/hierarchical-namespaces#209]
When trying to follow the user guide, I encounter an issue adding a Label/Annotation to a managed Namespace following the regex pattern I am willing to propagate. 
After adding the following `--managed-namespace-label=hier.mycorp.com/.*` as an argument to the HNC deployment. Adding the following label `hier.mycorp.com/test: "true"` will fail (it does not return any error, but the Label does not add to the Namespace).
I have checked the logs for any error but could not find any clue what caused the issue.

**Comment by adrianludwin** [comment]
Hi Raz, can I just confirm that you added the label in the
HierarchyConfiguration object, and *not* directly in the namespace itself?
Thanks!

**Comment by raz-bn** [comment]
Hey! 
thx for the quick replay. I missed the fact I need to add it to the HierarchyConfiguration.
tested it again, and it is working as expected. 
I'm closing the issue :)

**Comment by adrianludwin** [comment]
Great, thanks! Please reach out if you have any questions (or comments).
Cheers.

**Comment by adrianludwin** [comment]
Just a note about _why_ it works this way - we need to be able to tell the
difference between a valid managed label and an invalid one that needs to
be removed, so the source of truth can't be on the namespace label itself.
So it has to be somewhere else - either on a another annotations, or on a
separate object. Putting it in the HierarchyConfiguration object solves
that problem, and also lets us separate the permissions for "namespace
updater" from "managed label updater." TBH we're not certain exactly how
important that second feature is, but it seemed like a reasonable solution.
