### ISSUE TITLE
HNS and crossplane provider-kubernetes is not compatible

### ISSUE THREAD

**Issue by btwseeu78** [kubernetes-sigs/hierarchical-namespaces#215]
Hi All,

it seems there is issues if we use crossplane provider kuberntes together.I dont think its bug as per hns or how it works its fine but crossplane is used in our environment and its rapidly growing, as well as we are really interested using HNS and the plan was to use it via crossplane to give projects better reach but there is issues in it as of now,and i would love some feedback from community.
(crossplane creates the roles in all new namespaces for it to use)

**how to reproduce:**
1. install crossplane and provider-kuberntes
2. Configure provider kuberntes so it can create resources on all namespaces.clb + providerconfig
3.  kubectl hns set team-a --parent acme-org ( simply taken from examle)

![image](https://user-images.githubusercontent.com/9463052/176714677-4fbeef48-427c-409c-a726-890469f7492b.png)

but if we use kubectl hns create the it works with no problem.as roles are not injected yet.

![image](https://user-images.githubusercontent.com/9463052/176715150-3f7800c3-1acd-452c-bf98-39b78bb7bdcf.png)

so for existing namespaces if we want to adopt them part of the tree whats the approach we should take.

**Comment by adrianludwin** [comment]
Sorry for the delay in getting back to you. Does Crossplane put any labels or annotations on the objects it inserts into your namespaces? If so, we could extend K8s to support crossplane in the [same way we supported OpenShift and Rancher](https://github.com/kubernetes-sigs/hierarchical-namespaces/blob/master/internal/selectors/selectors.go#L170). Sadly, this isn't configurable today so we'd need to make a change to HNC. This will allow Crossplane to do its thing without HNC getting in the way.

wdyt?

**Comment by adrianludwin** [comment]
... we could also make this configurable, it's always been easier not to though until now :/

**Comment by btwseeu78** [comment]
To be precise its not actually crossplanes doing rather provider-Kubernetes ,its used to create Kubernetes resources that uses cross plane to do that, so for that it auto injects some permissions for all newly created ns so that it can create those resources on behalf.
Now the think i'm asking here is ,if there is an old namespace and i want to retain its previous bindings also take what hnc wants to add to it.

i think hnc working smooth as long as the ns are created gradually but its not working that way for already created.
im not sure what you guys wnat to do with this open or close i can understand its still new so it would require some time.so you may close this and take it as feedback maybe.as of now its not blocking anything on my prod.so we might have some time

**Comment by adrianludwin** [comment]
I'm afraid I don't really know anything about Crossplane and don't have time to look into it. I do think the fix would be fairly easy if Crossplane (or its K8s provider, I don't know what that means exactly) put an annotation on the the RBAC rolebindings. Do you know if this is true? If so, it's a one-line change to fix this in the next version of HNC.

**Comment by btwseeu78** [comment]
Crossplane does put role-binding on the roles injected by it.
![image](https://user-images.githubusercontent.com/9463052/186585681-2a0108e8-ce56-4257-9d25-8c7c36ea8938.png)

**Comment by btwseeu78** [comment]
This is the repo for crossplane provider-kuberntes:

https://github.com/crossplane-contrib/provider-kubernetes

just for information

**Comment by btwseeu78** [comment]
its because of this config on provider : https://github.com/crossplane-contrib/provider-kubernetes/blob/main/examples/provider/config-in-cluster.yaml.

i am exactly not sure if i am explaining the problem clearly. my question was if the NS already exists ,with some roles in it. is it possible to add it to the hnc tree,as sub namespace or as parent.

what hierarchy addition does actually to a ns is it juts adds some labels and annotations to justify depth ,parent child or there is some more stuff happening , if the roles are propagating then it should be append .I plan to dig out some more this weekend. If this is not satisfactory please let me know for info.
