### ISSUE TITLE
windows how to use hns within kubectl

### ISSUE THREAD

**Issue by yiqigao217** [kubernetes-sigs/hierarchical-namespaces#22]
<a href="https://github.com/JaneLiuL"><img src="https://avatars.githubusercontent.com/u/56822274?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [JaneLiuL](https://github.com/JaneLiuL)**
_Wednesday Nov 11, 2020 at 07:22 GMT_
_Originally opened as https://github.com/kubernetes-sigs/multi-tenancy/issues/1260_

----

Windows platform, when I download https://github.com/kubernetes-sigs/multi-tenancy/releases/download/hnc-v0.6.0/kubectl-hns_darwin_amd64 and put on the bin folder,  how to use
Now When I try "kubectl hns tree -A" on windows CMD, will fail said "Error: unknown command "hns" for "kubectl""

**Comment by yiqigao217** [comment]
<a href="https://github.com/adrianludwin"><img src="https://avatars.githubusercontent.com/u/20559844?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [adrianludwin](https://github.com/adrianludwin)**
_Wednesday Nov 11, 2020 at 18:46 GMT_

----

We don't pre-build Windows executables so the HNS plugin won't work on
Windows. If you have a Go toolchain you should be able to compile it for
yourself and it *should* work, but since none of the HNC developers have
Windows workstations, we're not able to test it ourselves. If you can build
it and it works, we can add it to our release process.

Will you be able to help with that?
Thanks!

**Comment by yiqigao217** [comment]
<a href="https://github.com/fejta-bot"><img src="https://avatars.githubusercontent.com/u/30488982?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [fejta-bot](https://github.com/fejta-bot)**
_Sunday Mar 14, 2021 at 20:36 GMT_

----

Issues go stale after 90d of inactivity.
Mark the issue as fresh with `/remove-lifecycle stale`.
Stale issues rot after an additional 30d of inactivity and eventually close.

If this issue is safe to close now please do so with `/close`.

Send feedback to sig-contributor-experience at [kubernetes/community](https://github.com/kubernetes/community).
/lifecycle stale

**Comment by yiqigao217** [comment]
<a href="https://github.com/yiqigao217"><img src="https://avatars.githubusercontent.com/u/51385444?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [yiqigao217](https://github.com/yiqigao217)**
_Tuesday Mar 16, 2021 at 13:42 GMT_

----

/remove-lifecycle stale

**Comment by garyhodgson** [comment]
Hi, for what it's worth, I could successfully get the hns plugin working on Windows 10 with the following steps:

* install go (https://golang.org/doc/install)
* clone this repo
* compile executable
```
GOOS=windows GOARCH=amd64 go build -o bin/kubectl/kubectl-hns.exe -ldflags="-X sigs.k8s.io/hierarchical-namespaces/internal/version.Version=latest" ./cmd/kubectl/main.go
```
* add kubectl-hns.exe to a $PATH directory
* update kubectl plugin list
```
kubectl plugin list
```

**Comment by adrianludwin** [comment]
Thanks! Are you able to make a PR? We'd want to modify both the Makefile,
the cloudbuild.yaml file, and (I think) the Krew manifest in the hack/
directory to include this.

**Comment by garyhodgson** [comment]
Hi, sorry, I wouldn't know what to put in a PR as I don't have experience with Google Cloud, etc.  My comment was just a drive-by observation as I am evaluating/learning k8s.

**Comment by adrianludwin** [comment]
Ok thanks Gary. You can feel free to add these instructions to the README
if you like, otherwise we'll just leave it commented here until someone
wants to work on this in the future.
