### ISSUE TITLE
Add documentation for inclusive propagation

### ISSUE THREAD

**Issue by adrianludwin** [kubernetes-sigs/hierarchical-namespaces#221]
/assign @mzeevi 

See https://github.com/kubernetes-sigs/hierarchical-namespaces/pull/217#pullrequestreview-1088726641

**Comment by adrianludwin** [comment]
@mzeevi I can't assign this to you formally but here it is FYI :)

**Comment by mzeevi** [comment]
Addressed this at #222, let me know what you think. @adrianludwin

**Comment by adrianludwin** [comment]
/remove-lifecycle rotten

This was actually fixed properly.
