### ISSUE TITLE
Internal error occurred: failed calling webhook

### ISSUE THREAD

**Issue by zybiko89** [kubernetes-sigs/hierarchical-namespaces#224]
`{"level":"error","ts":1661965729.2943187,"logger":"anchor.reconcile","msg":"while updating on apiserver","rid":88,"trigger":"cp/test-jk","error":"Internal error occurred: failed calling webhook \"objects.hnc.x-k8s.io\": Post \"https://hnc-webhook-service.hnc-system.svc:443/validate-objects?timeout=2s\": context deadline exceeded"}`

We're reinitializing our cluster from a backup of etc.d and we've run into a concern like shown above.  Is there a good mechanism for troubleshooting this type of concern?

**Comment by Alan01252** [comment]
I'm also looking into similar errors at the moment. HNC seems to be working correctly, but we get these errors occasionally in the manager log too.

Running on EKS version 1.0

**Comment by adrianludwin** [comment]
@Alan01252 interesting, how did you narrow this down to `RestartOnSecretRefresh`, just the prior log message? If that's the case, then this is harmless if annoying.

@zybiko89 does the problem eventually go away, or is it persistent? Webhooks can fail for an almost unlimited number of reasons so I'm not sure what would cause this, but as long as HNC's running and accessible from the control plane, these kinds of problems should be transient.

**Comment by zybiko89** [comment]
The issue was persistent for us but it won't be an issue for us going forward.

**Comment by Alan01252** [comment]
@adrianludwin I think the certificate might have been a red herring.  We're still crashing regularly in our preprod environment, but not in our prod.

The concerning thing for me is that this seems to cause the propagated resource to be deleted/rebuilt which is obviously not ideal when we've got things like network policies being propagated.

I'm still trying to ascertain what the difference between the environments is, they should be carbon copy of one another...

**Comment by erikgb** [comment]
@Alan01252 If you have cert-manager installed in your clusters, I can recommend switching to cert-manager for issuing webhook certificates. I've had a bunch of issues with the cert-rotator that HNC uses by default.....

**Comment by adrianludwin** [comment]
Using cert-manager as a more production-read system sgtm. cert-rotator is
designed as a simple batteries-included feature.

LMK if you find out what the difference is between the environments.

**Comment by Alan01252** [comment]
@adrianludwin one of our preprod nodes was running out of CPU and memory, which seemed to be impacting this pod more than others because we configure most pods without CPU limits just CPU resources for critical pods, but the yaml here enforces a limit.

Became way more obvious in ha mode

![image](https://user-images.githubusercontent.com/112859/192450970-f17964a6-0f77-4649-892a-775b66d8658c.png)
