### ISSUE TITLE
kubectl hns tree cmd is pretty slow

### ISSUE THREAD

**Issue by saradach** [kubernetes-sigs/hierarchical-namespaces#226]
Hi All,

We are in initial stage of implementation so we only have 15 HNS on one cluster and when running the kubectl hns tree cmd is pretty slow. 

We will be using this cmd heavily so is there any fix for this or any caching mechanism to make it fast?

**Comment by adrianludwin** [comment]
I didn't have any plans for this, can you describe your workflow a bit more? There are a bunch of questions about the command-line tools lately (e.g. #235), if we could get some volunteers to help contribute these features that might be helpful!

Even parallelizing the calls to the server might help somewhat, though that would only really help for wide trees.

**Comment by adrianludwin** [comment]
See also #223 and my comments there
