### ISSUE TITLE
Unable to deploy hnc to namespace other than hnc-system with `--enable-internal-cert-management`

### ISSUE THREAD

**Issue by AustinSmart** [kubernetes-sigs/hierarchical-namespaces#227]
The webhook cert rotator uses a `const` referring to `hnc-system` as the source of the namespace that hnc is deployed into ([ref 1](https://github.com/kubernetes-sigs/hierarchical-namespaces/blob/529259da83b27bf07191354789165767e1c3aaf3/internal/setup/webhooks.go#L26), [ref 2](https://github.com/kubernetes-sigs/hierarchical-namespaces/blob/529259da83b27bf07191354789165767e1c3aaf3/internal/setup/webhooks.go#L38)). I would expect references to resources consumed by hnc (`hnc-webhook-server-cert` in this case) should be made to the namespace in which the controller is deployed to by default, or at least be configurable.

This causes a `crashloopbackoff` of a deployment in a namespace other than `hnc-system` if the `--enable-internal-cert-management` [flag is set](https://github.com/kubernetes-sigs/hierarchical-namespaces/blob/529259da83b27bf07191354789165767e1c3aaf3/cmd/manager/main.go#L103).

```
{"level":"error","ts":1663007991.5142517,"logger":"cert-rotation","msg":"could not refresh cert on startup","error":"acquiring secret to update certificates: Secret \"hnc-webhook-server-cert\" not found","errorVerbose":"Secret \"hnc-webhook-server-cert\" not found\nacquiring secret to update certificates\ngithub.com/open-policy-agent/cert-controller/pkg/rotator.(*CertRotator).refreshCertIfNeeded.func1\n\t/workspace/vendor/github.com/open-policy-agent/cert-controller/pkg/rotator/rotator.go:215\nk8s.io/apimachinery/pkg/util/wait.ConditionFunc.WithContext.func1\n\t/workspace/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:220\nk8s.io/apimachinery/pkg/util/wait.runConditionWithCrashProtectionWithContext\n\t/workspace/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:233\nk8s.io/apimachinery/pkg/util/wait.runConditionWithCrashProtection\n\t/workspace/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:226\nk8s.io/apimachinery/pkg/util/wait.ExponentialBackoff\n\t/workspace/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:421\ngithub.com/open-policy-agent/cert-controller/pkg/rotator.(*CertRotator).refreshCertIfNeeded\n\t/workspace/vendor/github.com/open-policy-agent/cert-controller/pkg/rotator/rotator.go:247\ngithub.com/open-policy-agent/cert-controller/pkg/rotator.(*CertRotator).Start\n\t/workspace/vendor/github.com/open-policy-agent/cert-controller/pkg/rotator/rotator.go:179\nsigs.k8s.io/controller-runtime/pkg/manager.(*runnableGroup).reconcile.func1\n\t/workspace/vendor/sigs.k8s.io/controller-runtime/pkg/manager/runnable_group.go:218\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1581"}
```

**Comment by adrianludwin** [comment]
It doesn't surprise me that there are a few places where this is hardcoded.
I'd be happy to look at PRs to make it configurable, but I'm not sure how
to tell a pod what namespace it's running in (apart from through an env var
or command line arg or something). Also, all the configs would have to be
updated, I'm not sure if that's easy or hard offhand.

**Comment by AustinSmart** [comment]
[Using the downward API `fieldRef` `metadata.namespace` to populate an env var would be a nice way](https://kubernetes.io/docs/concepts/workloads/pods/downward-api/#downwardapi-fieldRef).

It looks like the `POD_NAMESPACE` env var is being used in other places ([ref 1](https://github.com/kubernetes-sigs/hierarchical-namespaces/blob/3d56dcf7a7c429018b10594a07af987d26b5b979/internal/webhooks/webhooks.go#L23), [ref 2](https://github.com/kubernetes-sigs/hierarchical-namespaces/blob/ec50308b39ae6ba63db6f34422639d4595fab880/internal/hierarchyconfig/validator.go#L457))

I will submit a PR if I have time.
