### ISSUE TITLE
Missing port 8081 in Manager manifest

### ISSUE THREAD

**Issue by lindhe** [kubernetes-sigs/hierarchical-namespaces#233]
The manager pod is using port 8081 for its health probes. That port is, however, not exposed to the user in the manifest, which makes it harder than necessary to know that the port is indeed open. 

I suggest that the port is added to the list of exposed ports in the container.

If other containers have the same situation, the same fix should go for them.

https://github.com/kubernetes-sigs/hierarchical-namespaces/blob/e9d8bb80e54ecfe735235ce608905e6dfbf757ca/config/manager/manager.yaml#L52-L58

**Comment by adrianludwin** [comment]
Oh, nice catch. Do you mind submitting a PR for that? Thanks!

Now I'm wondering - what does "exposing the port" in the YAML actually do? I thought it was necessary to make the port reachable, but if we're using it for health checks today, clearly it's already reachable?

**Comment by lindhe** [comment]
It's purely informative. 🙃 Kind of surprising at first. It's not only informative to humans, however. It is also informative to Services, which may refer to ports via their names (if they are named), which is convenient.

**Comment by adrianludwin** [comment]
Ah, good to know!
