### ISSUE TITLE
Do not propagate Helm release Secrets

### ISSUE THREAD

**Issue by iuriaranda** [kubernetes-sigs/hierarchical-namespaces#241]
Background info: Helm, by default, uses `Secrets` (of Type `helm.sh/release.v1`) to keep a history of the releases / charts deployed on the cluster. These secrets are stored in the namespace where their respective releases are deployed to.

There are already some [built-in exceptions](https://github.com/kubernetes-sigs/hierarchical-namespaces/blob/master/docs/user-guide/concepts.md#built-in-exceptions) in the HNC for resources that doesn't make sense to ever propagate, or that they can't be propagated at all. I believe Helm secrets should be included in those built-in exceptions, since I can't really conceive of any use-case where it makes sense to propagate them. It even adds some potential conflicts when they are propagated, for example running a `helm list -n some-ns` will show the releases deployed on namespace `some-ns` plus the ones deployed on all its parent namespaces. Also, the propagated Helm release Secrets won't be linked to anything deployed on the child namespace where they have been propagated to, so it could create some potential conflicts inside Helm as well.

Annotating each Helm release Secret to exclude it from being propagated is also not feasible, since it's Helm that manages those Secrets under the hood.

**Comment by mochizuki875** [comment]
I'll try to fix it.
/assign @mochizuki875

**Comment by mochizuki875** [comment]
@adrianludwin @iuriaranda 
I tried to fix it in #254.

**Comment by iuriaranda** [comment]
Nice! LGTM :tada:

**Comment by adrianludwin** [comment]
Thanks for this! It's merged.

/close
