### ISSUE TITLE
Update conflict error occur

### ISSUE THREAD

**Issue by mochizuki875** [kubernetes-sigs/hierarchical-namespaces#246]
### What happened?
Resource update conflict error occurs when create/delete `subnamespace`.

### What did you expect to happen?
This conflict error dosen't occur.

### How can we reproduce it (as minimally and precisely as possible)?
Create a `subnamespace`.

```console
$ kubectl hns create subns-a -n test
Successfully created "subns-a" subnamespace anchor in "test" namespace
```

Check `hnc-controller-manager` log.
```console
$ kubeclt -n hnc-system logs hnc-controller-manager-xxxxxxxx
...
{"level":"error","ts":1673418845.0319858,"logger":"hierarchyconfig.reconcile","msg":"while updating apiserver","rid":183,"ns":"subns-a","error":"Operation cannot be fulfilled on namespaces \"subns-a\": the object has been modified; please apply your changes to the latest version and try again"}
{"level":"error","ts":1673418845.113606,"logger":"controller.hierarchyconfiguration","msg":"Reconciler error","reconciler group":"hnc.x-k8s.io","reconciler kind":"HierarchyConfiguration","name":"hierarchy","namespace":"subns-a","error":"Operation cannot be fulfilled on namespaces \"subns-a\": the object has been modified; please apply your changes to the latest version and try again"}
...
```

This seems to occur probabilistically with the creation and deletion of `subnamespaces`.

### Kubernetes version

```console
$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.3", GitCommit:"434bfd82814af038ad94d62ebe59b133fcb50506", GitTreeState:"clean", BuildDate:"2022-10-12T10:57:26Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.3", GitCommit:"434bfd82814af038ad94d62ebe59b133fcb50506", GitTreeState:"clean", BuildDate:"2022-10-25T19:35:11Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"linux/amd64"}

$ kind version
kind v0.17.0 go1.19.2 linux/amd64
```

**Comment by mochizuki875** [comment]
I think these conflicts are caused by two reasons.

1. Concurrency of Reconcile
Some `Reconcile` run concurrently, so the same resource may be updated using `Update()` at the same time.

For example, 

`hierarchyconfig.Reconcile` may be run with 10 concurrency by default.
https://github.com/kubernetes-sigs/hierarchical-namespaces/blob/9102c4ddc2bbc145e279624d76d89f314a5485a6/config/manager/manager.yaml#L43-L51

`objects.Reconcile` created in `hncconfig.Reconcile` may be run with 10 concurrency by default.
https://github.com/kubernetes-sigs/hierarchical-namespaces/blob/9102c4ddc2bbc145e279624d76d89f314a5485a6/internal/hncconfig/reconciler.go#L341-L347


2. Difference between reality and cache
In Reconcile, controller retrieves resource instance using `Get()` and update resource using `Update()`.
Then, `Get()` method retrieves resource instance from `cache` synchronized with `kube-apiserver`.
So it may happen that resource instance is retrieved by `Get()` when cache sync is not completed.

https://pkg.go.dev/sigs.k8s.io/controller-runtime#hdr-Clients_and_Caches
> The default split client does not promise to invalidate the cache during writes (nor does it promise sequential create/get coherence), and code should not assume a get immediately following a create/update will return the updated resource.

**Comment by adrianludwin** [comment]
I'm not sure I understand this. Is it actually a problem, or does it just cause a brief blip in the logs? E.g. does the problem eventually go away on its own?

**Comment by mochizuki875** [comment]
@adrianludwin 
Thank you for your comments in #255 !
Before replying, I would like to discuss what this should be.

As you said, this issue is not directly related to the main HNC function. 
Because each reconciler will requeue the item and retry Reconcile, when a conflict error occurs.

And the error occurs probabilistically(e.g. I tried to create and delete subns 10 times and it occured about 4 times) from 2 reason I think:

1. Concurrency of Reconcile
2. Difference between reality and cache

  please see [here](https://github.com/kubernetes-sigs/hierarchical-namespaces/issues/246#issuecomment-1380552270) for details.

In #255, I tried to avoid resource update conflicts in these cases by replacing Update() with Patch() that only updates specific field because I think these error makes the logs messy and should not occur. 
However, since there is no problem functionally, I think that it is not necessary to fix it.
What do you think?

**Comment by adrianludwin** [comment]
I'd _rather_ leave this as-is since a) it's the standard way to build controllers using controller-runtime, I think, and b) to apply this fully across all the resource types owned by HNC is quite a lot of work and isn't done in #255 . So let's close this for now unless you'd like to continue the conversation. Thanks!

/close

**Comment by mochizuki875** [comment]
@adrianludwin 
I agree with your opinion.
Thank you for your consideration!
