### ISSUE TITLE
Publish binaries for linux/arm64

### ISSUE THREAD

**Issue by pickledcoder** [kubernetes-sigs/hierarchical-namespaces#248]
Hello,

The binary for the platform of `linux/arm64` seems to be [already built](https://github.com/kubernetes-sigs/hierarchical-namespaces/blob/master/Makefile#L125), however [it was not uploaded](https://github.com/kubernetes-sigs/hierarchical-namespaces/blob/master/cloudbuild.yaml).

Is it possible to upload this too?

I need it when running with Docker on Apple M1.

Thank you!

**Comment by adrianludwin** [comment]
Looks like we just need to add it here: https://github.com/kubernetes-sigs/hierarchical-namespaces/blob/master/cloudbuild.yaml#L80

Would you like to make a PR? It'll appear when we release HNC v1.1.

**Comment by pickledcoder** [comment]
Sure, [here is the PR](https://github.com/kubernetes-sigs/hierarchical-namespaces/pull/258)
