### ISSUE TITLE
`terminationGracePeriodSeconds` value not respected by HNC

### ISSUE THREAD

**Issue by DGodwin1** [kubernetes-sigs/hierarchical-namespaces#249]
## A description of the problem
Hi there, we're using HNC and have noticed that we experience WebhookAdmissionFailure issues when an HNC pod is being replaced as a part of a deployment rollout.

## Our current approach to solving this issue
When we add pre-stop hooks to the HNC deployment specification, we don’t see any webhook failures:
lifecycle:
      preStop:
       exec:
        command:
        - /bin/sh
        - -c
        - sleep 30s
We’re running this as high availability with 3 replicas for the webhooks.

## Our current understanding is that...
HNC does not seem to listen to the terminationGracePeriodSeconds value when it is set (we set it to 40s). We're not sure why, however, and wanted to raise it with you to begin a discussion / file as a bug.

**Comment by adrianludwin** [comment]
Hmm, sorry, I thought I replied to this last week.

I'm not sure what's happening here either - HNC just uses controller-runtime for all its basic infra, I don't know of anything that would interfere with this. Do you know if other controllers need to do something special to respect this, e.g. implement some kind of hook?

I'm afraid I also don't know much about this feature, can you explain why your `sleep 30` command fixes the problem? Thanks!

**Comment by adrianludwin** [comment]
@DGodwin1 did you ever figure this out?
