### ISSUE TITLE
parent access to resources in child needs to be greater than its own namespace

### ISSUE THREAD

**Issue by williamohara** [kubernetes-sigs/hierarchical-namespaces#259]
I am just discovering HNC - it feels solid but i am still learning it.

I am not sure if this use case is supported or not.

As a Parent - i want full access to my child but i don't need full access to myself.

to illustrate. i created tenant `lord-tenant-0` and a child tenant `super-tenant-1`

```
 $ kubectl hns tree lord-tenant-0
lord-tenant-0
└── [s] super-tenant-1
```

the role in question is called ` namespace-storage-read-role` and it looks like this:
```
$ kubectl describe roles/namespace-storage-read-role
Name:         namespace-storage-read-role
Labels:       app.kubernetes.io/managed-by=hnc.x-k8s.io
              hnc.x-k8s.io/inherited-from=lord-tenant-0
Annotations:  <none>
PolicyRule:
  Resources     Non-Resource URLs  Resource Names  Verbs
  ---------     -----------------  --------------  -----
  configmaps.*  []                 []              [list get]
  secrets.*     []                 []              [list get]
```

when i look at the child namespace, the role is propagated as expected:
```
$ kubectl config set-context --current --namespace=super-tenant-1
Context "core-cluster" modified.

$ kubectl describe rolebindings/tenant-service-role-binding
Name:         tenant-service-role-binding
Labels:       app.kubernetes.io/managed-by=hnc.x-k8s.io
              hnc.x-k8s.io/inherited-from=lord-tenant-0
Annotations:  <none>
Role:
  Kind:  Role
  Name:  namespace-storage-read-role
Subjects:
  Kind            Name                         Namespace
  ----            ----                         ---------
  ServiceAccount  subscripify-service-account  lord-tenant-0
```

but I want `lord-tenant-0:subscripify-service-account` to have *more* access to its child's account storage i.e. adding `create, delete, patch`

is there any way to propagate higher levels of access downward?

**Comment by adrianludwin** [comment]
Hey, sorry I didn't get to this for so long - a bit of maintainer burnout :/

I'm not really sure I understand what you're trying to do? _Namespaces_ don't have access; humans and service accounts do. So I'd imagine that you'd create two roles in the parent namespace - readonly, and read-write.  And then create a rolebinding to the service account in the parent namespace; that should propagate to the descendants. Does that work?

/remove-lifecycle stale
