### ISSUE TITLE
HNC: test function TearDownHNC can fail silently

### ISSUE THREAD

**Issue by yiqigao217** [kubernetes-sigs/hierarchical-namespaces#26]
<a href="https://github.com/adrianludwin"><img src="https://avatars.githubusercontent.com/u/20559844?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [adrianludwin](https://github.com/adrianludwin)**
_Friday Aug 21, 2020 at 14:55 GMT_
_Originally opened as https://github.com/kubernetes-sigs/multi-tenancy/issues/1041_

----

/cc @GinnyJI 
/cc @yiqigao217 

Ginny and I were looking at a test where it _seems_ like the command to delete the subns CRD failed (as evidenced by the fact that there were still subnses afterwards) but because we use `TryRunQuietly` there was no evidence of this.

We should have some better function that can delete objects if they exist, but if they _can't_ delete an object, return an error.

**Comment by yiqigao217** [comment]
<a href="https://github.com/adrianludwin"><img src="https://avatars.githubusercontent.com/u/20559844?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [adrianludwin](https://github.com/adrianludwin)**
_Friday Aug 21, 2020 at 14:55 GMT_

----

/good-first-issue

**Comment by yiqigao217** [comment]
<a href="https://github.com/k8s-ci-robot"><img src="https://avatars.githubusercontent.com/u/20407524?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [k8s-ci-robot](https://github.com/k8s-ci-robot)**
_Friday Aug 21, 2020 at 14:55 GMT_

----

@adrianludwin: 
	This request has been marked as suitable for new contributors.

Please ensure the request meets the requirements listed [here](https://git.k8s.io/community/contributors/guide/help-wanted.md#good-first-issue).

If this request no longer meets these requirements, the label can be removed
by commenting with the `/remove-good-first-issue` command.


<details>

In response to [this](https://github.com/kubernetes-sigs/multi-tenancy/issues/1041):

>/good-first-issue


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by yiqigao217** [comment]
<a href="https://github.com/mayankshah1607"><img src="https://avatars.githubusercontent.com/u/30319228?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mayankshah1607](https://github.com/mayankshah1607)**
_Sunday Sep 06, 2020 at 12:46 GMT_

----

Hi @adrianludwin , I'd like to give this issue a try. :) 
I just looked into the code, and I see that we have an alternate function `TryRun` that logs the errors when the command returns an error. Is there any reason why we may not be able to use this?
Thanks

**Comment by yiqigao217** [comment]
<a href="https://github.com/adrianludwin"><img src="https://avatars.githubusercontent.com/u/20559844?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [adrianludwin](https://github.com/adrianludwin)**
_Sunday Sep 06, 2020 at 16:23 GMT_

----

Hey Mayank, sorry I've been on vacation this last week. I'll reply when I'm
back after Labour Day (i.e. early next week). Thanks!

**Comment by yiqigao217** [comment]
<a href="https://github.com/mayankshah1607"><img src="https://avatars.githubusercontent.com/u/30319228?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mayankshah1607](https://github.com/mayankshah1607)**
_Sunday Sep 06, 2020 at 17:19 GMT_

----

No problem. Have a great vacation! 🙂

**Comment by yiqigao217** [comment]
<a href="https://github.com/adrianludwin"><img src="https://avatars.githubusercontent.com/u/20559844?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [adrianludwin](https://github.com/adrianludwin)**
_Tuesday Sep 08, 2020 at 12:12 GMT_

----

Hey let me know if you need any advice on this but any PRs would be welcome!

**Comment by yiqigao217** [comment]
<a href="https://github.com/mayankshah1607"><img src="https://avatars.githubusercontent.com/u/30319228?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mayankshah1607](https://github.com/mayankshah1607)**
_Tuesday Sep 08, 2020 at 12:15 GMT_

----

Hi, @adrianludwin . Thanks!
I was just trying to wrap my head around this issue, and tried to look into the code. The issue mainly talks about how the tests did not leave any evidence when the CRD deletion failed (due to `TryRunQuietly`). 
I see that we have an alternate function called `TryRun` that will log these failures. Would it help if we used `TryRun` instead?

**Comment by yiqigao217** [comment]
<a href="https://github.com/adrianludwin"><img src="https://avatars.githubusercontent.com/u/20559844?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [adrianludwin](https://github.com/adrianludwin)**
_Tuesday Sep 08, 2020 at 12:32 GMT_

----

I believe the problem is that we _expect_ some of the commands in the cleanup to fail - e.g., if we try to delete a namespace that we never created. In those cases, I think we do want `TryRunQuietly` to avoid printing too much logspam. However, if the namespace _does_ exist, it should be deleted successfully.

I think you're also looking at another bug that has a better way to clean up the namespaces without relying on exact names. If so, running that command with `TryRun`, and not `TryRunQuietly`, seems like the right thing to do.

**Comment by yiqigao217** [comment]
<a href="https://github.com/fejta-bot"><img src="https://avatars.githubusercontent.com/u/30488982?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [fejta-bot](https://github.com/fejta-bot)**
_Tuesday Mar 02, 2021 at 06:39 GMT_

----

Issues go stale after 90d of inactivity.
Mark the issue as fresh with `/remove-lifecycle stale`.
Stale issues rot after an additional 30d of inactivity and eventually close.

If this issue is safe to close now please do so with `/close`.

Send feedback to sig-contributor-experience at [kubernetes/community](https://github.com/kubernetes/community).
/lifecycle stale

**Comment by yiqigao217** [comment]
<a href="https://github.com/yiqigao217"><img src="https://avatars.githubusercontent.com/u/51385444?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [yiqigao217](https://github.com/yiqigao217)**
_Tuesday Mar 16, 2021 at 15:10 GMT_

----

/remove-lifecycle stale

**Comment by xinydev** [comment]
I think this issue can be closed because there is no call to the function `TearDownHNC ` anymore.

**Comment by adrianludwin** [comment]
If that's the case we should delete the function :) Would you like to do the honours?

**Comment by xinydev** [comment]
> If that's the case we should delete the function :) Would you like to do the honours?

Sure, 😊
