### ISSUE TITLE
Question: List all resources in subtree?

### ISSUE THREAD

**Issue by blakjak44** [kubernetes-sigs/hierarchical-namespaces#272]
Hi, is there a way to list all resources within the subtree of a namespace? Similar to `kubectl get -n <namespace> all`, it would be great if you could run `kubectl hns get <namespace> all` and have it list all resources in `<namespace>` and its descendants.

**Comment by adrianludwin** [comment]
This is hard, but @cmurphy is now working on it: https://github.com/kubernetes-sigs/hierarchical-namespaces/pull/281
