### ISSUE TITLE
Simple way to know HierarchicalResourceQuota status

### ISSUE THREAD

**Issue by mochizuki875** [kubernetes-sigs/hierarchical-namespaces#274]
## Overview
When using `HierarchicalResourceQuota`, resource quotas is applied across parent and child `Namespaces`.
However, there is no way to know the quota and consumption of resource in the `HierarchicalResourceQuota` other than check the detail.
This may confuse users, so I think there should be a simple way to know it(like `kubectl get resourcequotas`).

## Detail
For example, there are two `Namespaces` with hierarchy like this.
If `HierarchicalResourceQuota` of `limits.cpu=1` is applied to the parent test `Namespace`, the total amount of CPU available across parent and child `Namespaces` is 1. 

```
test
└── subns-a
```

Now, the result of `kubectl get hierarchicalresourcequotas` is this.
We can't know the quota and consumption of resource.
```
$ kubectl get hierarchicalresourcequotas -n test
NAME       AGE
test-hrq   80s
```

To know that, we need to check the detail of `HierarchicalResourceQuota`.
In this case, the total CPU concumption across parent and child `Namespace` is 500m/1.
```
$ kubectl describe hierarchicalresourcequotas test-hrq -n test
Name:         test-hrq
Namespace:    test
Labels:       <none>
Annotations:  <none>
API Version:  hnc.x-k8s.io/v1alpha2
Kind:         HierarchicalResourceQuota
...
Spec:
  Hard:
    limits.cpu:  1
Status:
  Hard:
    limits.cpu:  1
  Used:
    limits.cpu:  500m
Events:          <none>
```

In addition, if we check the `ResourceQuota` of each `Namespace` that are automatically created in each `Namespace` when we create `HierarchicalResourceQuota`, the result is this.

```
$ kubectl get resourcequotas -n test
NAME               AGE   REQUEST   LIMIT
hrq.hnc.x-k8s.io   16s             limits.cpu: 500m/1

$ kubectl get resourcequotas -n subns-a 
NAME               AGE   REQUEST   LIMIT
hrq.hnc.x-k8s.io   19s             limits.cpu: 0/1
```

These status do not fully reflect quotas by `HierarchicalResourceQuota`.
In this case,  it looks like this:
  - test Namespace: 500m remaining CPU available
  - subns-a Namespace: 1 CPU available

However, the actual available CPU  is 500m across these `Namespaces`.

## Expectation

I think there should be a simple way to know `HierarchicalResourceQuota` status like this.
```
NAME               AGE   REQUEST   LIMIT
test-hrq           50s             limits.cpu: 500m/1
``````

**Comment by mochizuki875** [comment]
kind/feature

**Comment by mochizuki875** [comment]
I tried using JsonPath with `HierarchicalResourceQuota`'s `CustomResourceDefinition`(.spec.versions.additionalPrinterColumns field), but I couldn't come up with an expression to control what is displayed.
In this case, we need to control the value to display depending on whether each field under `spec.hard` exists.  


So I propose a new sub-command of `kubectl-hns` in the following format to view the status of `HierarchicalResourceQuota`.

```
kubectl-hns hrq [NAME] [flags]
```

For Example
```
$ kubectl hns hrq -n test
NAME         AGE     REQUEST                                              LIMIT
test-hrq     2m37s   requests.cpu: 500m/1, requests.memory: 100Mi/200Mi   limits.cpu: 500m/2, limits.memory: 100Mi/500Mi
test-hrq-2   4m6s    requests.memory: 100Mi/300Mi                         limits.cpu: 500m/1

$ kubectl hns hrq test-hrq -n test
NAME       AGE     REQUEST                                              LIMIT
test-hrq   2m43s   requests.cpu: 500m/1, requests.memory: 100Mi/200Mi   limits.cpu: 500m/2, limits.memory: 100Mi/500Mi

$ kubectl hns hrq --all-namespaces
NAMESPACE   NAME         AGE     REQUEST                                              LIMIT
test        test-hrq     2m49s   requests.cpu: 500m/1, requests.memory: 100Mi/200Mi   limits.cpu: 500m/2, limits.memory: 100Mi/500Mi
test        test-hrq-2   4m18s   requests.memory: 100Mi/300Mi                         limits.cpu: 500m/1
```

**Comment by mochizuki875** [comment]
@adrianludwin 
PTAL?  
How do you think this?

**Comment by zfrhv** [comment]
hii
im not sure how to display exactly output as the ResourceQuota, but we can try to put the next field in the hrq crd:
```yaml
spec:
  versions:
  - name: v1alpha2
    additionalPrinterColumns:
    - description: blah blah
      jsonPath: .status.hard
      name: Hard
      type: string
    - description: blah blah
      jsonPath: .status.used
      name: Used
      type: string
```

**Comment by mochizuki875** [comment]
@zfrhv 
Thanks for your comment!
Yes, as you say, it is possible to display `.status.hard` and `.status.used` by using `additionalPrinterColumns` like this.

```console
$ kubectl get hierarchicalresourcequotas.hnc.x-k8s.io -n test
NAME       HARD                                                                                      USED
test-hrq   {"limits.cpu":"2","limits.memory":"500Mi","requests.cpu":"1","requests.memory":"200Mi"}   {"limits.cpu":"500m","limits.memory":"100Mi","requests.cpu":"500m","requests.memory":"100Mi"}
```

However, I don't know how to display exactly output as the ResourceQuota...(said [here](https://github.com/kubernetes-sigs/hierarchical-namespaces/issues/274#issuecomment-1537657937))

If it needed, I'll add this:)

**Comment by adrianludwin** [comment]
Sorry I didn't respond on the bug, but the PR looks fantastic and I've approved it. Can you please cherry-pick it to v1.1 as well? Thanks!

**Comment by adrianludwin** [comment]
I wouldn't worry too much about making this exactly like the RQ output. For now, it's human output, and machines can use the json representation.

**Comment by mochizuki875** [comment]
> Can you please cherry-pick it to v1.1 as well?

@adrianludwin 
Thanks!
My friend @keisukesakasai did it for me :)
Please check it.
#284

**Comment by mochizuki875** [comment]
These PR have merged and I'll close this issue.
#283
#295 

/close
