### ISSUE TITLE
ns describe quota used not update

### ISSUE THREAD

**Issue by j0rGeT** [kubernetes-sigs/hierarchical-namespaces#275]
I found that when the hrq quota is used, the quota information used in describe ns is not updated. After the quota used in the child ns is updated, the value of used in the parent ns is still 0。

parent-ns:
```bash
root@saar-virtual-machine:~# kubectl describe ns kubecube-workspace-workspacez5
Name:         kubecube-workspace-workspacez5

Resource Quotas
 Name:                    hrq.hnc.x-k8s.io
 Resource                 Used  Hard
 --------                 ---   ---
 limits.cpu               0     2
 limits.memory            0     500Mi
 requests.cpu             0     2
 requests.memory          0     500Mi
 requests.nvidia.com/gpu  0     0`
```

sub-ns:
```bash
root@saar-virtual-machine:~# kubectl describe ns kubecube-project-projectz1
Name:         kubecube-project-projectz1
Status:       Active

Resource Quotas
 Name:                    hrq.hnc.x-k8s.io
 Resource                 Used  Hard
 --------                 ---   ---
 limits.cpu               1     2
 limits.memory            100M  500Mi
 requests.cpu             1     2
 requests.memory          100M  500Mi
 requests.nvidia.com/gpu  0     0
```

**Comment by zfrhv** [comment]
true, also mentioned in #274 
when describing the ns it displays the ResourceQuota and not the HierarchicalResourceQuota
so the values in the ResourceQuita are not updated

**Comment by mochizuki875** [comment]
`HierarchicalResourceQuota` seems to be implemented by the combination of `ResourceQuota` and Admission Webhook.
`ResourceQuota` is namespaced resource and just control the namespace's resource consumption.
So if child ns is updated, it is not reflected in parent ns.
It is reflected to `HierarchicalResourceQuota`'s status field.

**Comment by adrianludwin** [comment]
Yeah, `hrq.hnc.x-k8s.io` is just the per-namespace _implementation_ of the HRQ - it has no visibility into what's happening in the rest of the hierarchy.  But @mochizuki875 's amazing PR (#283)  will at least make it easy to understand what's there.

Perhaps we should give that RQ a more descriptive name - e.g. `local-impl.hnc.x-k8s.io` would more clearly emphasize that you shouldn't trust the data in here. wdyt?

(Sorry for the delays, just some maintainer burnout)

**Comment by zfrhv** [comment]
@adrianludwin 
thats a very good idea

**Comment by keisukesakasai** [comment]
@adrianludwin 
Hi, I will try to fix this. Is "local-impl." OK?

/assign @keisukesakasai

**Comment by adrianludwin** [comment]
Maybe it's nice to get the word "hrq" in there was well - e.g. if `local-impl-hrq` lgty, then I'm good with it too. Thanks!

**Comment by zfrhv** [comment]
@adrianludwin 
@keisukesakasai 
maybe its better to include the original namespace name in which hrq is created, or the hrq resource name?
for example: `<namespace name>-hrq-local-imp`
just in case there are multiple hrqs in the namespace tree.

for example in this case:
```
grandpa (has hrq)
├─ father1 (has hrq)
│  ├─ son1
│  ├─ son2
├─ father2
```
there should be 2 ResourceQuotas in namespace `son1`, and they cant have the same name
(if i correctly understand how it works)

**Comment by adrianludwin** [comment]
HNC combines the limits from `grandpa` and `father1` already, so we can't name it after the "real" object's namespace because there could be multiple of them.

**Comment by mochizuki875** [comment]
For this issue, we should add some kind annotation to document as discussed https://github.com/kubernetes-sigs/hierarchical-namespaces/pull/301#issuecomment-1738301338.

**Comment by mochizuki875** [comment]
Close this issue as #340 has been merged.
/close
