### ISSUE TITLE
Built-in propagation exceptions and the "propagate.hnc.x-k8s.io/all" annotation

### ISSUE THREAD

**Issue by duduedri96** [kubernetes-sigs/hierarchical-namespaces#276]
Version v1.1.0-rc2

I have a use case in which a Rancher cluster creates RoleBindings on my project-managed namespace, and I would like to have child namespaces to this parent namespace which will get those RoleBindings. The parent namespace is controlled by Rancher, and all role bindings should be propagated to the children.
The documentation states that Rancher resources that contain the `cattle.io/creator=norman` label are excluded by default. This prevents me from implementing my use case.

After diving a bit in the code, I figured out that if I'll have the `propagate.hnc.x-k8s.io/all=true` annotation on my resource it will be propagated, even with the default `Propagate` mode that RoleBindings get implicitly. I tested it out and it works. The reason it works is that the `ShouldPropagate` function checks for this `propagate.hnc.x-k8s.io/all=true` annotation before it figures out if the resource contains one of the excluded labels.

The documentation [clearly states](https://github.com/kubernetes-sigs/hierarchical-namespaces/blob/master/docs/user-guide/how-to.md#limit-the-propagation-of-an-object-to-descendant-namespaces) that the `propagate.hnc.x-k8s.io/all` annotation is useful only in the `AllowPropagate` propagation mode. This clearly isn't the case here, since RoleBindings use the `Propagate` mode.

The question is which part is wrong here - the documentation which should be updated to indicate this, or the code which shouldn't allow those resources to be propagated with the `propagate.hnc.x-k8s.io/all` annotation since they have a label which should be excluded by default? In other words, can I rely on this behavior to stay as is on future versions?

Thanks.

**Comment by adrianludwin** [comment]
lol! That's a great corner case. On the one hand, the code is wrong - we never _intended_ to override the default exclusion. However, it looks like you've discovered a nice use case for the "bug" - it can override the default behaviour when that's not what you want.

What if we made this the official behaviour? That is, automatically-excluded objects are now only excluded _by default_, but you can override this with the annotation. Or would that not be useful enough?

I don't know much about Rancher. Can you explain why other Rancher users may have wanted this exclusion, and why this doesn't apply to your use case?

**Comment by duduedri96** [comment]
Hi!
About your question, yes, it may be useful to be able to leave this behavior and make it official by letting HNC to propagate such excluded resources with this `all` annotation - however it makes things a bit messy for our use case, because the resources in question are created by Rancher itself, and I would need to cause them to have this annotation somehow (e.g. with a mutating admission webhook).

As far as I can see, preventing Rancher resources from being propagated was added as part of #104. Their use case is a bit different from ours - they want Rancher to manage all Role/RoleBindings, but other stuff by HNC.

Let me give you a bit of a background - Rancher groups namespaces in a concept called "Project". They are used merely for grouping namespaces for RBAC purposes (a Project resides inside a specific cluster - it doesn't cross cluster boundaries). For example, group four namespaces in one project, assign permissions to this project, and users who have permissions to the project will have those permissions on the namespaces which are part of this project inside their cluster.

In our use case, we use Rancher as a single point of access to a fleet of clusters. The users log in, and then they have access to all of their clusters. Rancher has an "authentication proxy" - users login to Rancher, and they get a kubeconfig from Rancher that communicates with their cluster **through** Rancher. As part of cluster creation we create a single Project for the users on each of the clusters, and a single namespace within that project. From that point onwards, Rancher manages the permissions to this project (and to the namespace) by creating an illusion that a single user (RBAC-wise) communicates with the clusters, even though behind the scenes Rancher creates an impersonation that represents the user inside the various clusters. It knows how to manage RBAC RoleBindings in order to create this behavior.

We don't want users to mess with Rancher other than this authentication & authorization trick. We want users to be able to create namespaces by themselves, in GitOps, by defining SubnamespaceAnchors in their parent namespace (which is part of the project we created for them). We want them to have access to those namespaces their created as subnamespaces, and in order to have that working, we must let HNC propagate all RoleBindings to the child namespaces. We have other resources that we want to be propgated, e.g. NetworkPolicies, and we rely on HNC for this as well.

Thus, having HNC propagate RoleBindings which were created by Rancher, is useful for us. We can use this behavior I mentioned in this issue, however as I mentioned above, it'll require us to create some admission webhook to resolve that. Having something like #280, to disable the exclusion on our clusters, will be a lot helpful.

Thanks!

**Comment by rjbez17** [comment]
What are you using for K8s policy controls? Kyverno can handle the mutation for you along without having to write your own controller. 

I'm a bit hesitant to keep the bug around since it seems like one of those things that will come back to bite us later and was never the intention. @adrianludwin do you have any strong opinion s here?

**Comment by rjbez17** [comment]
Sorry, missed the actual PR. Since the exclusion list is just a key value label, is there any reason we shouldn't move the list of exclsusions to the config file? We can have the current rancher label in the config by default but it would allow @duduedri96 to remove it and get what they want?

**Comment by adrianludwin** [comment]
Two thoughts on this...

* @duduedri96 - we don't _really_ recommend checking `SubnamespaceAnchor`s into Git - see https://github.com/kubernetes-sigs/hierarchical-namespaces/blob/master/docs/user-guide/best-practices.md#gitops. It's better to check in the namespace directly along with the `HierarchyConfiguration` object. Would this help your problem?
* @rjbez17 - we definitely can and should move the exclusions to the command line args. I'd happily approve a PR for that! Just no time to work on it myself.

**Comment by adrianludwin** [comment]
The assumption was that ArgoCD/FluxCD had cluster-wide access and so could directly create namespaces. If that's not possible, then you're right - subnamespaces are the only way to go.

Checking in anchors should work - it's just that there are more moving parts (e.g. the namespaces don't actually get created right away, which could cause problems) and we haven't always committed to supporting every feature on `HierarchyConfiguration` in `SubnamespaceAnchor` as well because we didn't know of a good usecase.

But what you're saying makes sense, if the CD doesn't have cluster access. Do you want to update the docs?

**Comment by duduedri96** [comment]
@adrianludwin our ArgoCD setup restricts the GitOps repositories from creating non-namespaced resources (such as namespaces) so this is why it makes sense in our case to use the anchors. 
Not sure though how not using them would resolve the issue, since we still need HNC to propagate Rancher's RoleBindings. 

Thanks!

**Comment by adrianludwin** [comment]
@duduedri96 ok thanks. Just thought I'd check!

Do you want to try moving the entire list of exceptions to command-line flags?

**Comment by duduedri96** [comment]
@adrianludwin I will try to find some time to do that and will open a PR. 
I'm also working on my CLA to be signed.

**Comment by duduedri96** [comment]
@adrianludwin , I just opened #293 that moves the list of exceptions to be a command line flag.
