### ISSUE TITLE
Highly Available HNC controller

### ISSUE THREAD

**Issue by prateekn** [kubernetes-sigs/hierarchical-namespaces#278]
Hey Team,

Wanted to check if its feasible to run more than one replica of the hnc controller?

https://github.com/kubernetes-sigs/hierarchical-namespaces/releases/download/v1.0.0/default.yaml
the hnc-controller-manager controller has replica set to 1 in the default manifest.

wanted to know, if the  hnc-controller-manager controller can handle > 1 replica count.

Thanks

**Comment by zfrhv** [comment]
hello
in the releases -> assets:
https://github.com/kubernetes-sigs/hierarchical-namespaces/releases

you can see that there is actually file called `ha-experumental.yaml`:
https://github.com/kubernetes-sigs/hierarchical-namespaces/releases/download/v1.1.0-rc2/ha-experimental.yaml

I tried it in my environment and it deployed multiple replicas, is that what you are looking for?

the only disadvantage is that its still experimental, and the quotas are also experimental, so its or multiple replicas or single replica with quota features.
personally im waiting until one of them will become stable and then we can use multiple replicas + HNQ

**Comment by prateekn** [comment]
@zfrhv This is exactly what I was looking for, but looks like will need to wait it out till its GA to deploy it on only production cluster!!

**Comment by zfrhv** [comment]
same, im waiting too
the owners of this repo dont seem to have much time,
I think we will have to contribute somehow

**Comment by adrianludwin** [comment]
Hey all, I'm the owner and yes, I've had a bit of maintainer burnout, sorry about that! Trying to catch up on everything now.

There's no known problems with HA, we just didn't want to mark it as "GA" right away! But if you've tried it and it works for you, I think you should feel confident to use it. If we get one or two more folks to try it out, we'll go ahead and mark it as GA, likely in v1.2.

As for HRQ, sorry I still don't have v1.1 out, I'll try to get it out shortly.

**Comment by zfrhv** [comment]
i used it for a week, and it worked great. seems stable 
(only a week cuz i need hrq)

**Comment by wSedlacek** [comment]
The `hnc-controller-manager-metrics-service` appears twice in the `ha.yaml` and it causing issue with my tooling.
Both configurations of the `hnc-controller-manager-metrics-service` are the same.
