### ISSUE TITLE
Enable per namespace by annotation

### ISSUE THREAD

**Issue by norman-zon** [kubernetes-sigs/hierarchical-namespaces#282]
I would like to suggest an alternative way of selecting which namespaces to enable HNC for by a label instead of the `--excluded-namespace` and `--included-namespace-regex`.

We create namespaces from a Terraform module, but only want to enable HNC for a subset of all our namespaces. 
For me it would feel most intuitive to add a toggle to the Terraform module which adds a label to the namespace (e.g. `hnc.x-k8s.io/enabled = "true"`). The HNC would be installed with a flag like `--include-namespaces-by-label`. So the controller would only pick up the namespaces with the label and ignore all others.

Please consider this for future development.

EDIT: I just found the [hnc.x-k8s.io/included-namespace](https://github.com/kubernetes-sigs/hierarchical-namespaces/blob/master/docs/user-guide/concepts.md#hncx-k8sioincluded-namespace-label-on-namespaces) label, which basically does what I want, except that it can't be used manually (meaning separately from the `include/exclude` flags) , from what I understand.

EDIT2:

I tried combining -`-included-namespace-regex=""` with manually setting `hnc.x-k8s.io/included-namespace: "true"` on a namespace which resulted in:

```
Could not create subnamespace anchor.
Reason: admission webhook "subnamespaceanchors.hnc.x-k8s.io" denied the request: subnamespaceanchors.hnc.x-k8s.io "test" is forbidden: cannot create a subnamespace in the unmanaged namespace "test" (does not match the regex set by the HNC administrator: `^""$`)
```

So I really would love to have some kind of `--include-namespaces-by-label`flag for the controller, that changes this behaviour.

**Comment by adrianludwin** [comment]
@norman-zon Thanks for this suggestion! The reason the labels are an _output_ of HNC, not an input, is that we don't want anyone who can set labels on namespaces to be able to turn off enforcement by HNC. I suppose that for clusters where most users aren't allowed to modify namespaces, this might not be so important - is that the case you're in?

If so, you could modify [this webhook](https://github.com/kubernetes-sigs/hierarchical-namespaces/blob/97817c0339a99fce606ef1b96df4ebe08148fd21/internal/namespace/validator.go#L169) (flag-controlled) to turn off the behaviour of setting `included-namespace` by default, and allow the user to set it themselves. I'd be happy to accept that for a future release if you want to make a PR - if you do this, please update the docs as well, together with the warnings about the security hole this creates.

**Comment by norman-zon** [comment]
@adrianludwin Thanks for explaining the rationale behind this design approach. You are right, our usecase would be a cluster where users can't manually modify namespaces. All namespace changes have to be done through terraform via PRs. So the security impact would be tolerable.

I will have a look into the code. But I am not sure if I will be able to implement the changes myself, as my experience with Go is very limited.

**Comment by adrianludwin** [comment]
Sounds good! Unfortunately I don't have the bandwidth to make these kinds of changes myself but I can help review anything you send me.
