### ISSUE TITLE
Activate HRQ E2E test

### ISSUE THREAD

**Issue by mochizuki875** [kubernetes-sigs/hierarchical-namespaces#296]
HRQ E2E test is pending now.
By adding HRQ to v1.1 as a new feature, should we activate it?

https://github.com/kubernetes-sigs/hierarchical-namespaces/blob/168dd7ebae3a6fd47bdbb649b44d5f96aa1a05c5/test/e2e/hrq_test.go#L31-L33

**Comment by mochizuki875** [comment]
@adrianludwin 

Is it related?

>  I'm going to have to enable HRQ by default before these tests will pass though so I'll work on that next.

https://github.com/kubernetes-sigs/hierarchical-namespaces/pull/289#issuecomment-1579690774

**Comment by adrianludwin** [comment]
I've changed my mind, I think HRQ should be opt-in for v1.1, then on by default in v1.2. So we can activate the e2e tests on `master`.

**Comment by adrianludwin** [comment]
/assign

These are all working except one test, I _think_ because the number of default secrets in the namespace has changed. I'll update the test to be robust to this.

**Comment by mochizuki875** [comment]
@adrianludwin 
Thanks for your answer and I see.
