### ISSUE TITLE
Add labels/annotations to the subnamespace (or its anchor) at creation time

### ISSUE THREAD

**Issue by fpoirotte** [kubernetes-sigs/hierarchical-namespaces#305]
Hello,

I would like to be able to define labels/annotations for a new subnamespace at the time it is created.
Something along the lines of:
```sh
kubectl hns create -n parent child --annotation foo=bar --annotation baz=qux --label tata=titi --label toto=tutu
```

Currently, this requires first creating the subnamespace, then updating it to add the annotations/labels.
I was hoping that the two operations could be merged into one.

What do you think?

**Comment by adrianludwin** [comment]
The raw capability for this already exists: the `SubnamespaceAnchor` has label and annotation fields [here](https://github.com/kubernetes-sigs/hierarchical-namespaces/blob/564b4a968ca2091f27cf0eb51d0cd99190e57db5/api/v1alpha2/subnamespace_anchor.go#L73). Adding command-line flags to `kubectl-hns` to populate those seems like a good idea and quite easy to do - please feel free to add that!

**Comment by adrianludwin** [comment]
Sorry for the delay - you need to use `spec.labels`, not `metadata.labels`, see my latest comment in #323.
