### ISSUE TITLE
`kubectl hns delete` command?

### ISSUE THREAD

**Issue by superbrothers** [kubernetes-sigs/hierarchical-namespaces#307]
While `kubectl hns create` command exists, `hns delete` command does not.

We can delete subns with `kubectl delete subns` command. However, a user using `kubectl hns` command for the first time will assume that since `create` exists, `delete` must exist, but will be confused because it does not.

**Comment by adrianludwin** [comment]
I'm ok with a pass-through command. We could also add an
--allow-cascading-deletion flag that automatically calls "kubectl hns set
--allow-cascading-deletion" to combine two calls into one.

**Comment by superbrothers** [comment]
OK, I will try to implement it.

**Comment by adrianludwin** [comment]
Thanks!
