### ISSUE TITLE
v1.1.0 binary does not run on Debian Bullseye

### ISSUE THREAD

**Issue by joekohlsdorf** [kubernetes-sigs/hierarchical-namespaces#308]
The published binary for v1.1.0 for AMD64 requires GLIBC 2.32 or 2.34 but Debian Bullseye has 2.31.
Debian Bookworm was only published ~2 weeks ago so in my opinion it isn't reasonable to already expect everyone to be on the latest version.

Error message:
```
./kubectl-hns: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./kubectl-hns)
./kubectl-hns: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./kubectl-hns)
```

To reproduce wit Docker put the following in a `Dockerfile` and run `docker build .`:
```
FROM debian:bullseye
ADD https://github.com/kubernetes-sigs/hierarchical-namespaces/releases/download/v1.1.0/kubectl-hns_linux_amd64 /kubectl-hns
RUN chmod +x ./kubectl-hns
RUN ./kubectl-hns help
```

The simplest fix is probably to use an older OS to compile the binary.

**Comment by adrianludwin** [comment]
That's odd, we haven't updated the build containers since February or so.
Do you know when GLIBC 2.32 was released?

**Comment by joekohlsdorf** [comment]
I was previously running 1.1.0rc2 which works. I just tested rc3 and found that it has he same issue.
So if you updated the build containers in February just after publishing rc2 then that is likely the change which introduced this incompatibility.

**Comment by argais** [comment]
Running into the same thing with GitHub self hosted runners. 

```
/home/runner/.krew/bin/kubectl-hns: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /home/runner/.krew/bin/kubectl-hns)
/home/runner/.krew/bin/kubectl-hns: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /home/runner/.krew/bin/kubectl-hns)
```

**Comment by Yayg** [comment]
Hi, Same problem here on Rocky 8.7.

**Comment by adrianludwin** [comment]
Ok I'll go see if I can downgrade somehow

**Comment by adrianludwin** [comment]
Sorry I haven't gotten to this yet :( Will have another look.

**Comment by yyj1827** [comment]
Hi, Same problem here .
[root@cs-xndb1 ~]# kubectl hns --help
/usr/local/sbin/kubectl-hns: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by /usr/local/sbin/kubectl-hns)
/usr/local/sbin/kubectl-hns: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by /usr/local/sbin/kubectl-hns)
[root@cs-xndb1 ~]# cat /etc/redhat-release
CentOS Linux release 7.6.1810 (Core)

**Comment by iamasmith** [comment]
@mist714 raised an PR for this which was merged on the 14th November 2023 which builds the binaries with CGO_ENABLED=0 so should avoid these issues with glibc completely.
This merge, however, was after v1.1.0 was built and released so the binaries available are linked with glibc still.
For the time being people may want to try building from source themselves.

**Comment by iamasmith** [comment]
Looks like little interest in this feature.

**Comment by iamasmith** [comment]
@joekohlsdorf yes, I think it was me that pointed this out
