### ISSUE TITLE
hns CLI: describe command should also describe allowCascadingDeletion property

### ISSUE THREAD

**Issue by manjinder-mckc** [kubernetes-sigs/hierarchical-namespaces#319]
**Current Output:**
```
$ kubectl hns describe boss                             
Hierarchy configuration for namespace boss
  Parent:  bigboss
  Children:
  - workers (subnamespace)
  No conditions
```
**Expected Output:**
```
$ kubectl hns describe boss                             
Hierarchy configuration for namespace boss
  Parent:  bigboss
  Children:
  - workers (subnamespace)
  AllowCascadingDeletion: true
  No conditions
```

Proposing Changes here: https://github.com/kubernetes-sigs/hierarchical-namespaces/blob/564b4a968ca2091f27cf0eb51d0cd99190e57db5/internal/kubectl/describe.go#L33-L83

Would be willing to raise a PR, if you guys agree that this makes sense.

**Comment by adrianludwin** [comment]
I'm not seeing the code that actually prints out `AllowCascadingDeletion` but that feature does look like a good idea, I'll review it if you send me a PR, thanks! One minor nit, maybe use human words, e.g. `Allows cascading deletion` instead of `AllowCascadingDeletion`.
