### ISSUE TITLE
Move Prow and Testgrid configs out of wg-multi-tenancy

### ISSUE THREAD

**Issue by adrianludwin** [kubernetes-sigs/hierarchical-namespaces#32]
Anyone who goes hunting in the kubernetes/test-infra repo for HNC will be looking for the name of this repo (`hierarchical-namespaces`), not the old repo (`wg-multi-tenancy`). I think it makes sense to move the HNC configs out of:

* https://github.com/kubernetes/test-infra/tree/master/config/jobs/kubernetes-sigs/wg-multi-tenancy
* https://github.com/kubernetes/test-infra/tree/master/config/testgrids/kubernetes/wg-multi-tenancy

And into `hierarchical-namespaces` instead.

**Comment by adrianludwin** [comment]
wdyt?

**Comment by rjbez17** [comment]
Yeah I agree. We are our own sub project now so shouldn't be an issue to get that setup.
