### ISSUE TITLE
Don't require an explicit namespace label to exclude webhooks

### ISSUE THREAD

**Issue by adrianludwin** [kubernetes-sigs/hierarchical-namespaces#33]
The v0.8 implementation of our webhooks was for an 'excluded-namespace' label, which means we need to _explicitly_ label namespaces (like `kube-system`) that we _don't_ want to be affected by HNC. However, a better solution might be to use the list of excluded namespaces on the command-line as the only source of truth, and have HNC automatically _add_ a label to all namespaces that it _does_ manage, and then have the webhooks look for that label instead.

This would remove the need for users to take any explicit steps to exclude critical namespaces. It also gives us a nice path to ensure the object webhook doesn't operate in externally-managed namespaces.

/milestone v0.9
/assign @yiqigao217

**Comment by yiqigao217** [comment]
Closing this to consolidate with #9
