### ISSUE TITLE
No metadata.namespace field in the HierarchyConfiguration CRD jsonschema

### ISSUE THREAD

**Issue by hrk091** [kubernetes-sigs/hierarchical-namespaces#332]
HierarchyConfiguration CRD is patched to make it singleton by https://github.com/kubernetes-sigs/hierarchical-namespaces/blob/master/hack/crd_patches/singleton-enum-patch.sh, but metadata.namespace field is not defined there. While HNCConfiguration is global singleton, HierarchyConfiguration is namespaced singleton so there should be metadata.namespace field in the HierarchyConfiguration CRD.

Now I’m trying validate manifests including HierarchyConfiguration resources using `kubeconfirm`, and it has reported the following Error:

```
HierarchyConfiguration hierarchy is invalid: problem validating schema. Check JSON formatting: jsonschema: '/metadata' does not validate with file:///generated/crd_schemas/eval/hierarchyconfiguration-hnc-v1alpha2.json#/properties/metadata/additionalProperties: additionalProperties 'namespace' not allowed
```

It seems that the namespace property needs to be added [here](https://github.com/kubernetes-sigs/hierarchical-namespaces/blob/master/hack/crd_patches/hierarchy_singleton_enum.yaml) as follows:

```diff
            # This is patched by hack/crd_patches/singleton-enum-patch.sh
            properties:
              name:
                type: string
                enum:
                  - hierarchy
+             namespace:
+               type: string
```

**Comment by adrianludwin** [comment]
I'm not sure I understand - there's tons of stuff in the metadata other than just name and namespace. Why don't they need to be added as well?

**Comment by hrk091** [comment]
Thank you for your reply!

Right. It is much better that other stuff in the metadata are also added. 
In my case, only name and namespace are defined in the metadata of HierarchyConfiguration in my GitOps repository, and the manifests stored in the Git repository are validated by kubeconfirm in CI, not the actually applied one. Therefore, the only error regarding namespace has been reported.
