### ISSUE TITLE
order in subnamespaceanchor deletion

### ISSUE THREAD

**Issue by wibed** [kubernetes-sigs/hierarchical-namespaces#344]
issue subnamespaces with a mount point to be deleted before others, to prevent blocking finalizers freezing the command

**Comment by wibed** [comment]
i meant for namespaces that contain resources such as pvc

**Comment by adrianludwin** [comment]
Can you describe a scenario where this happens? A tree of
subnamespaces should be deleted from the root on down, and I thought PVCs
could only be used from within their own namespace, so there shouldn't be
any cross-namespace dependencies, or at least that's what I thought. If you
could describe exactly what happens, and in what order, that would be
helpful. Thanks!

**Comment by wibed** [comment]
of course
heres is an example:

```yaml
staging
├── [s] cert-manager
├── [s] csi-driver-nfs
├── [s] docker-registry
├── [s] gitsrv
├── [s] kubernetes-replicator
├── [s] metallb-system
└── [s] traefik
```

docker-registry and gitsrv do have a pvc mounted managed by csi-driver-nfs,
i must have been overworked at the moment this presented itself to me as a problem, 
because i should use csi-driver-nfs outside of the staging namespace. 

my bad! thank you for your time

**Comment by adrianludwin** [comment]
Oh, I see - it's not the PVC itself being used from the wrong namespace,
it's the CSI driver. So you're concerned that if csi-driver-nfs is deleted
before docker-registry and gitsrv, which have PVCs managed by that CSI,
that we won't be able to delete the PVCs anymore? Yes, I agree that's a
problem, but you'd have the same problem without HNC as well, right? E.g.
if you just say "kubectl delete ns csi-driver-nfs docker-registry gitsrv",
you'd still have the same race condition, correct?

**Comment by wibed** [comment]
indeed. but i wouldnt be exposed to the user friendlyness of a collective namespace such as 
hnc provides.

**Comment by adrianludwin** [comment]
Ok - I think it would be pretty challenging for HNC to automatically figure
out the relationships. Maybe we could give guidance that dependencies like
CSI drivers should be in parent namespaces, and then put finalizers between
all objects and those subnamespaces, but that sounds pretty dangerous too.
LMK if you have any ideas!

**Comment by wibed** [comment]
i too came to the conclusion that guidance would be the most one could do at this point.

if it demands `privileged` it should be in a parent namespace or something like that.

**Comment by adrianludwin** [comment]
sgtm, thanks!
