### ISSUE TITLE
Is it possible to use the kubectl-hns plugin in API form?

### ISSUE THREAD

**Issue by kyungminchoi** [kubernetes-sigs/hierarchical-namespaces#345]
hello. I have a question.
Is it possible to use the kubectl-hns plugin in REST API form?
For example, currently I am using client-go to call the k8s api when creating a namespace within an application developed in the go language. I would like to modify the part that creates this namespace to the code that creates a subnamespace.

**Comment by adrianludwin** [comment]
If you're using client-go, your best option is probably just to create the
HNC API objects directly and send them through the generic client - that's
what the HNS plugin does. I doubt any of the internal code would add much
value to you, it's a pretty straightforward translation of command-line to
API.

**Comment by zuspiel** [comment]
Hi @adrianludwin,
first off: Stellar effort on this project!

I'd also like to drive HNS via the API. We programmatically create compute "jobs" (which are basically entire applications). Each job works in its own namespace. HNS is a god-sent for managing permissions.

I've been looking at the documents that get created when assembling a hierarchy via `kubectl`. I think I can possibly reverse engineer the API calls, but it'll be a lot of trial and error. I also tried added verbosity (like `kubectl -v=8` which normally shows the API calls) but that option isn't available in the HNS plugin.

Is there anything you could point us at that would help in divining the correct API calls? 

Thanks a bunch in advance!
