### ISSUE TITLE
Use the default namespace in the kubeconfig

### ISSUE THREAD

**Issue by superbrothers** [kubernetes-sigs/hierarchical-namespaces#347]
hns command will fail to execute if the `-namespace` option is not specified.

```
$ kubectl hns create foo
Error: parent must be set via --namespace or -n
```

On the other hand, kubectl uses the default namespace set in kubeconfig if not specified. I think hns command's behavior should be aligned with kubectl's.

What do you think?

**Comment by yanggangtony** [comment]
+1
Make sense for me.

**Comment by superbrothers** [comment]
I'll make a PR.

**Comment by yanggangtony** [comment]
I have done it. wait.

**Comment by superbrothers** [comment]
OK. Thanks.
