### ISSUE TITLE
Exceptions support for GVK

### ISSUE THREAD

**Issue by RealHarshThakur** [kubernetes-sigs/hierarchical-namespaces#41]
Currently, we have support for exceptions but only for a particular resource . It would be nice to have it for entire GVK since we don't have support for multiple `HNCConfiguration` . 

If we had multiple `HNCConfiguration`, here's what I would do :
* I would like to have the `HNCConfiguration` named `config-A` which can propagate config maps/secret/custom resource , roles and rolebindings . 
* For the second `HNCConfiguration`  named `config-B` , I don't want to propagate the  config map/secret/custom resource objects , but just the roles/rolebindings . 

It might be relatively simpler to have support for exceptions for GVK as opposed to having different configs.

**Comment by adrianludwin** [comment]
Thanks @RealHarshThakur. Just a small correction - every namespace can have a [`HierarchyConfiguration`](https://github.com/kubernetes-sigs/hierarchical-namespaces/blob/ba15870be8ba46b259891c1cd55634e7e438d62c/api/v1alpha2/hierarchy_types.go#L108), which currently only has two interesting fields:
* The parent of the namespace
* Whether or not cascading deletion is enabled

GVK propagation (technically Group/Resource propagation) is currently controlled by [`HNCConfiguration`](https://github.com/kubernetes-sigs/hierarchical-namespaces/blob/ba15870be8ba46b259891c1cd55634e7e438d62c/api/v1alpha2/hnc_config.go#L133). There's only one `HNCConfiguration` object per cluster.

From an API perspective, we _could_ take the `HNCConfigurationSpec` object, duplicate it, and add it to `HierarchyConfiguration`. This would allow every namespace to indicate which kinds of resources it wants to propagate.

The problem then becomes: how do we handle conflicts and changes?
* If the cluster-wide config says `secrets` should be in the `Remove` mode, can a namespace override it?
* If you move a namespace from a parent that doesn't propagate `secrets` to another parent that does, and this would cause a secret in the child namespace to be overwritten, [would we catch that](https://github.com/kubernetes-sigs/hierarchical-namespaces/blob/ba15870be8ba46b259891c1cd55634e7e438d62c/internal/validators/hierarchy.go#L249)? What about in that namespace's descendants?
* Should you be able to turn on propagation of some object type that hasn't been allowed by the cluster admin? E.g. can I turn on propagation for `Pod` in my namespace (a terrible idea) without my cluster admin approving that first?

So from an API perspective, I think we can make this work pretty easily. The complicated bit is going to be defining what the _behaviour_ should be and then implementing that robustly. Does that all make sense?
