### ISSUE TITLE
 Cannot create namespace

### ISSUE THREAD

**Issue by twendt** [kubernetes-sigs/hierarchical-namespaces#64]
We are currently testing with a build from the master branch.

We are not able to create a namespace outside of hnc anymore:

```
# kubectl create ns test
Error from server (Forbidden): error when creating "da79dac9-6411-4608-8405-7eead44462d2.yaml": admission webhook "namespaces.hnc.x-k8s.io" denied the request: You cannot change the value of the "hnc.x-k8s.io/included-namespace" label. It has to be set as true on a non-excluded namespace. See https://github.com/kubernetes-sigs/hierarchical-namespaces/blob/mast
er/docs/user-guide/concepts.md#included-namespace-label for detail.
```

We also have an issue with the new feature about the include-namespace label. We are using Azure Kubernetes Service and there it sometimes happens that Azure creates a new namespace in the cluster. This for instance happens when the Azure Policy for AKS addon is being enabled on the cluster.
With the current implementation that would mean that the new namespace would be automatically included by hnc.

Maybe it would be an option to disable the automatic inclusion with a flag and require the label to be set on creation. All namespaces that do not have the label would be excluded apart from all namespaces that are created by hnc itself.

**Comment by adrianludwin** [comment]
Do you have the mutating admission webhook set up correctly, e.g. did you use the latest HNC manifests to install HNC? The mutating webhook should add `hnc.x-k8s.io/included-namespaces = true` to _all_ namespaces, including the ones that are created via `kubectl create ns`.

**Comment by twendt** [comment]
@adrianludwin Thank you very much. We simply replaced the image of the hnc manager. I now added the mutating webhook configuration and now it works as designed.

**Comment by adrianludwin** [comment]
Great, glad to hear!

/close
