### ISSUE TITLE
(Metrics User Guide) Fix link to stackdriver metrics

### ISSUE THREAD

**Issue by rjbez17** [kubernetes-sigs/hierarchical-namespaces#7]
The old link here: https://github.com/kubernetes-sigs/multi-tenancy/blob/master/doc/metrics/stackdriver-gke.md

Is not a 404, need to find where it went and update the docs to point to it here:

https://github.com/kubernetes-sigs/hierarchical-namespaces/blob/master/docs/links.md

**Comment by adrianludwin** [comment]
Looks like it's here:
https://github.com/kubernetes-sigs/multi-tenancy/blob/master/incubator/hnc/docs/user-guide/how-to.md#admin-metrics
