### ISSUE TITLE
How handle duplicate DNS names on shared environment with CoreDNS?

### ISSUE THREAD

**Issue by olljanat** [kubernetes-sigs/hierarchical-namespaces#79]
HNC looks like very good solutions for adding extra abstraction layer to more easily define different environments for different purposes. However after playing for a while with it I ended up to thinking that what is best way to handled DNS records on case where multiple copies of same service run on same cluster?

Example if I would have simple setup like this which contains separate dev and prod organizations and both of those would have one application which have separate frontend and backend namespaces:
```
$ kubectl hns tree dev-org
dev-org
├── dev-team-a
|   ├── dev-app1-frontend
|   └── dev-app1-backend
└── dev-team-b
    ├── dev-app2-frontend
    └── dev-app2-backend

$ kubectl hns tree prod-org
prod-org
├── prod-team-a
|   ├── prod-app1-frontend
|   └── prod-app1-backend
└── prod-team-b
    ├── prod-app2-frontend
    └── prod-app2-backend
```

Because namespaces much be unique on cluster level I need add those `dev-` and `prod-` prefixes to all namespaces which also means that app1 frontend cannot call its backend services with DNS names like `<service-name>.app1-backend.svc.cluster.local` which it would be able to do in case of separate dev and prod clusters but instead of environment specific names `<service-name>.dev-app1-backend.svc.cluster.local` / `<service-name>.prod-app1-backend.svc.cluster.local` are needed which is very bad solution as it makes applications configuration much more complex.

I can see from https://coredns.io/plugins/kubernetes/ that it is possible to configure CoreDNS to host separate zones based on namespace labels with config like this:
```yaml
kubernetes   dev.local {
    namespace_labels env=dev
}
kubernetes   prod.local {
    namespace_labels env=prod
}
```
but still those namespace prefixes remains as a problem.

Is there some plans to handle this use case? I think that CoreDNS need to be done aware of HNS/namespace prefixes (as it actually is possible use same config even without HNS).

**Comment by olljanat** [comment]
It looks to be that CoreDNS [rewrite plugin](https://coredns.io/plugins/rewrite/) most probably can be used to remove those `dev-` / `prod-` prefixes from `dev.local` / `prod.local` DNS domains but those DNS domains still need to be added to pods `searches` list ( https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-dns-config ) and currently it is needed to be done separately to each of service as it is not possible to define those on namespace level.

**Comment by adrianludwin** [comment]
I'm afraid I'm not an expert in CoreDNS. Is it possible to configure CoreDNS from a K8s controller (like HNC)? HNC isn't popular enough for CoreDNS to try to support it, but CoreDNS is certainly popular enough that HNC could try to configure it!

**Comment by olljanat** [comment]
CoreDNS part looks to be working rewrite policy like this:
```
rewrite stop {
  name regex (.*)\.(.*)\.dev.local {1}.dev-{2}.svc.cluster.local
  answer name (.*)\.dev-(.*)\.svc\.cluster\.local {1}.{2}.dev.local
}
```
then names like `<service name>.app1-backend.dev.local` starts working.

And it should be possible (have not tested yet) to update pods DNS search list using [Kyverno](https://kyverno.io) policy like this:
```yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-searches
spec:
  background: false
  rules:
  - name: add-searches
    match:
      resources:
        kinds:
        - Pod
        namespaces:
        - "dev-*"
    mutate:
      patchStrategicMerge:
        spec:
          dnsConfig:
            searches:
              - dev.local
```

which makes `<service name>.app1-backend` working.

So it looks that I have solution to my use case but is this something which should be written to documentation and/or should there be some kind of ready make example with all pieces in-place?

**Comment by adrianludwin** [comment]
Sorry for the delay, I was on vacation for two weeks.

It would be awesome if you could contribute some documentation, maybe [here](https://github.com/kubernetes-sigs/hierarchical-namespaces/blob/master/docs/user-guide/best-practices.md)? Feel free to keep it short and even refer back to this issue if you like to save yourself some work, as long as this issue is easy to find, I think that's the most important thing.
