### ISSUE TITLE
Don't throw away errors from ShouldPropagate

### ISSUE THREAD

**Issue by adrianludwin** [kubernetes-sigs/hierarchical-namespaces#82]
See [comment](https://github.com/kubernetes-sigs/hierarchical-namespaces/pull/80#discussion_r712641064). We're discarding errors but we shouldn't be; they should be <strike>propagated upwards like any other error or at _least_ </strike> logged as an error **(Update Sep 25 - we should log them, see discussion below)**.

/cc @joe2far

**Comment by yashvardhan-kukreja** [comment]
Hi @adrianludwin 👋🏼 
At the time of error, should I proceed towards just logging the error and letting the loop iterate further, or should I actually, break the loop right away by returning the error hence, making it propagate upwards in the call stack?

I prefer the latter one but as I am new, I might be missing something so I'd love to hear your suggestion :)

**Comment by adrianludwin** [comment]
Ok I had a look and I can see why we're not propagating these up. The scenario where you could get an error is:
* Someone puts a bad selector on an object. This should never happen, but let's say there was a bug and one got in.
  * This selector is basically now ignored
* Someone tries to validate another change that _might_ affect this object (or one of its propagated copies). We call `ShouldPropagate` to see if there's a conflict, but instead we get the error due to the actions of the earlier editor.

In this case, we should _not_ propagate the error back upwards, as it would effectively block everyone _else_, without giving them any way to resolve the issue. This seems suboptimal.

Instead, I'd vote for logging the error, e.g. something like this:

`log.Error(err, "Invalid selector")`

That way, if the admin is monitoring errors, they'll get a flood of them whenever we _might_ be making the wrong choice - which is exactly what we want. The `log` object isn't currently passed down to the places that call `ShouldPropagate` but this should be easy to solve.

The one downside here is that it looks like the name of the object that has the bad selector isn't going to be identified. We could add it individually to each of the places where we log the error, but IMO it's better to add this information to the error itself when they're first generated, i.e. in [GetSelector](https://github.com/kubernetes-sigs/hierarchical-namespaces/blob/b35e79d3a0d50e8353cf13ea073aa5251b113ca8/internal/pkg/selectors/selectors.go#L115), [GetTreeSelector](https://github.com/kubernetes-sigs/hierarchical-namespaces/blob/b35e79d3a0d50e8353cf13ea073aa5251b113ca8/internal/pkg/selectors/selectors.go#L56) and [GetNoneSelector](https://github.com/kubernetes-sigs/hierarchical-namespaces/blob/b35e79d3a0d50e8353cf13ea073aa5251b113ca8/internal/pkg/selectors/selectors.go#L138). Each of these functions (which are the only ones that can cause an error in `ShouldPropagate`) know the object that's causing the error, so [IMO that's the right place to report it](https://twitter.com/aludwin/status/1438958350759256065).

To take the simplest example of `GetNoneSelector`, I'd change

```
		return false,
			fmt.Errorf("invalid %s value: %w",
				api.AnnotationNoneSelector,
				err,
			)
```

with something like this:

```
		return false,fmt.Errorf("invalid %s value on %s/%s (%s): %w",
			api.AnnotationNoneSelector, inst.GetNamespace(), inst.GetName(), inst.GroupVersionKind(), err)
```

Which will give a string like `invalid propagate.hnc.x-k8s.io/none value on foo-ns/bar (Secret): <lower level error>`. In `GetTreeSelector` the error can be returned from many different places so you'll probably want to precreate the string `"%s/%s (%s)` but that's pretty easy to do.

I wouldn't worry about testing this _too_ much, since we're just talking about improving an error message and logging messages that got away. If you like, you could create a bad selector on an object by disabling all the webhooks, making a bad change, and then re-enabling the webhooks and checking the logs, but it's not strictly necessary.
