### ISSUE TITLE
Replace excluded-namespace label with included-namespace

### ISSUE THREAD

**Issue by yiqigao217** [kubernetes-sigs/hierarchical-namespaces#9]
<a href="https://github.com/yiqigao217"><img src="https://avatars.githubusercontent.com/u/51385444?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [yiqigao217](https://github.com/yiqigao217)**
_Friday Apr 30, 2021 at 16:22 GMT_
_Originally opened as https://github.com/kubernetes-sigs/multi-tenancy/issues/1503_

----

Consider excluding namespaces with K8s 1.21+ namespace metadata.name label - 
See https://github.com/kubernetes/kubernetes/issues/92157#issuecomment-825160958

**Comment by yiqigao217** [comment]
<a href="https://github.com/yiqigao217"><img src="https://avatars.githubusercontent.com/u/51385444?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [yiqigao217](https://github.com/yiqigao217)**
_Friday Apr 30, 2021 at 20:07 GMT_

----

Another thought is that instead of using `excluded`, maybe use `included`? Considering the damage it could cause if the system namespaces are not labeled as excluded.

HNC can add the `included` label to all namespaces except those flagged as excluded-namespaces in HNC `container.args`. Then our object webhook can remain fail CLOSE and use that label instead.

**Comment by yiqigao217** [comment]
(The `app.kubernetes.io/managed-by` label may be a good option, but ACM already uses it on namespaces created from the repo. In that case, when HNC works with ACM in the same cluster, HNC actually "manages" the namespace but cannot have the `app.kubernetes.io/managed-by: hnc.x-k8s.io` on that namespace.)

Since this label is mainly for the object webhook to decide whether to enforce policy on the namespaces, we may name it as **`hnc.x-k8s.io/webhooks-enforced`**?

The `excluded-namespace` container args in the HNC deployment manifest is the only source-of-truth. HNC won't reconcile these namespaces or objects in these namespaces.

As for the currently used `hnc.x-k8s.io/excluded-namespace` label introduced in v0.8, we will depreciate it in v0.9 since this is a non-breaking change.

WDYT @rjbez17 @adrianludwin

**Comment by rjbez17** [comment]
Sorry, I never hit submit last week. Yes, I do agree with this approach. Would we use a mutating WH on the NS object to add the label? Do it in reconciliation later? I assume it will also disallow removing the label/re-add it?

**Comment by adrianludwin** [comment]
... but we should add a webhook to prevent users from modifying these
labels as well (I think there's another bug about stopping people from
modifying tree labels too).

Ryan, any thoughts on webhooks-enforced vs webhooks-enabled? I'm also
thinking that it's a bit weird that this label only controls _one_ webhook
(the object webhook) so maybe we need a more specific name? Maybe
hnc.x-k8s.io/included-namespace (opposite of the --excluded-namespace
command-line flag)?

**Comment by rjbez17** [comment]
Yea I was just going to suggest something like `hnc.x-k8s.io/is-excluded` or `hnc.x-k8s.io/hnc-managed` but `hnc.x-k8s.io/included-namespace` works as well. It would also make it more clear to admins what the label is for without having to dive into docs.

**Comment by yiqigao217** [comment]
`hnc.x-k8s.io/included-namespace` as opposite of the `--excluded-namespace` command-line flag sgtm! Will update the PR #36
