### ISSUE TITLE
Subnamespace Labels are missing when listed as namespace

### ISSUE THREAD

**Issue by shivamverma182** [kubernetes-sigs/hierarchical-namespaces#90]
We are thinking of adopting HNC in our kubernetes clusters. While playing around the namespaces and subnamespaces. I found when you set some labels on subnamespaces, these labels are available when you read those subnamespaces as subnamespaces(kubectl get subns -n parent-ns --show-labels). But when you read subnamespaces as actual namespaces(kubectl get ns child-ns --show-labels), the labels are missing.

Similarly, If you apply any label via namespace(kubectl label ns child-ns role=backend). You won't be able to read labels via subnamespaces(kubectl get subns -n parent-ns --show-labels).

![image](https://user-images.githubusercontent.com/10782660/136563705-79fe309c-1d37-48d3-9169-4ae290453426.png)

Any help would be appreciated.

**Comment by adrianludwin** [comment]
Hey @shivamverma182. The "subnamespace" object is actually a SubnamespaceAnchor object - that it, it's an object that _represents_ the namespace, but it's not a namespace itself. So labels that you put on the subns are not propagated to the namespace or vice versa; this is expected.

This is the same as a Deployment object vs a Pod from that deployment. If you put a label on the Deployment, it is _not_ propagated to the Pod. To get a label onto the Pod, you must put the label inside the podspec _inside_ the Deployment object.

We don't have a similar feature for SubnamespaceAnchors, although we've considered adding one. Can you explain what your use case is for it? And would you be willing to make a PR for that feature?

**Comment by marandalucas** [comment]
Hello @adrianludwin! We love this project! We are implementing HNC in our cluster, however we have the same issue that @shivamverma182

One of our requirement is add the label ** istio-injection: enabled **. We would like that you reconsider to implement this feature in SubnamespaceAnchor Objects or another way to propagate labels from parents Namespace. (Https://github.com/kubernetes-sigs/hierarchical-namespaces/issues/47).

We think that it should be:

`---
apiVersion: hnc.x-k8s.io/v1alpha2
kind: SubnamespaceAnchor
metadata:
  namespace: sp-int
  name: sp-int-sandbox
  labels:
    istio-injection: enabled` 

Right Now our workaround would be to configure Istio to propagate this header in all the namespaces by default and exclude others (We are applying the SubnamespaceAnchor using GitOps with ArgoCD).

Thanks for all

**Comment by adrianludwin** [comment]
Hey @marandalucas and @shivamverma182 , I'm implementing label propagation in #47. You can't add them in the `SubnamespaceAnchor` yet, but you _can_ add them in the `HierarchyConfiguration` object in the _parent_ namespace which will make it automatically apply to all descendant namespaces.

I'm going to close this bug, can you please comment on #47 to let me know if that would suite your needs or not? Thanks!

/close
